### ISSUE TITLE
build system

### ISSUE THREAD

**Issue by unikzforce** [jhipster/jhipster-dotnetcore#1]
appreciate the work you do here,
i suggest the [cakebuild](https://cakebuild.net) as the build system,
but i think the gradle ecosystem has something for dotnet too.

**Comment by unikzforce** [comment]
it also has some template for Rider and resharper and ...:
[cake-build/frosting](https://github.com/cake-build/frosting)

**Comment by danielpetisme** [comment]
Thank you for the proposal and sorry for the response latency.
I'll have a look (and feel free to propose a PR!).

**Comment by unikzforce** [comment]
As I see that the project is migrating to .Net Core 3, then this article seems more relevant:

[You don’t need Cake anymore; the way to build .NET projects going forward.](https://pknopf.com/post/2019-03-10-you-dont-need-cake-anymore-the-way-to-build-dotnet-projects-going-forward/)

**Comment by danielpetisme** [comment]
Definitively I'll have a look

**Comment by matkoch** [comment]
Ping me if you have questions about nuke.

**Comment by danielpetisme** [comment]
Thank you for your proposition! Fancy a PR?

**Comment by matkoch** [comment]
No time unfortunately :) But all questions are welcome.

**Comment by danielpetisme** [comment]
The current build system looks good enough, I close for now the issue
