### ISSUE TITLE
Support more databases

### ISSUE THREAD

**Issue by BananeGuimauve** [jhipster/jhipster-dotnetcore#10]
One of the features asked by many people is the possibility to choose more databases.
In order to make it, Entity Framework Core will be really helpfull and will facilitate their integration.
Currently, the only choice is a Sqlite database stored in RAM.

**Comment by ivanmonteiro** [comment]
Hi, I'm adding some questions to the discussion:
**Any chances to supporting a NoSql database such as MongoDB?** 
I'm not sure if Entity Framework Core supports it.

**Comment by danielpetisme** [comment]
The NoSQL support would be awesome but it requires some time we (the current team) don't have 
We will focus on what EF Core supports out of the box, if Mongo is covered by EF Core it will definitively ease the job.

With our current capacity and if it's not covered by EF, I don't think it would be feasible before early next year (we focus on delivery we can't star too many features in parallel)

@Ivan feel free to propose a PR for Mongo if it's important to you.The dotnetcore blueprint is a community effort. We'll be happy to help/ease new contributions. We even can add some bounties ($$$) to motivate devs :wink:

**Comment by ivan** [comment]
putting @ivan into GitHub emails the wrong Ivan

**Comment by ItsInsajd** [comment]
Hello,

So me and @kosnkow were checking out capabilities of this blueprint and  we discovered the only BD  available atm is SQLite. It would be a nice learning experience to work on this blueprint, so we are thinking about adding support for other databases, relational for now to  make things easier. So my question is, is anyone from the team already working on such feature? 

If not, I would like to know if you have any guidelines on how to work on such  blueprint? As far as we noticed, the workflow would require changes in DatabaseStartup.cs.ejs, appSettings and of course some other switches between used nuget packages, etc. So let's say we would add support for mssql for now. Should we make changes in existing files? Or add separate templates? We want to keep EFCore as an ORM.

**Comment by nicolas63** [comment]
It's good initiative :smiley: ! Nobody work on it currently. I think you can change existing file and add conditions to choose database type

**Comment by ItsInsajd** [comment]
#75

**Comment by danielpetisme** [comment]
Fix #75
