### ISSUE TITLE
Blazor Issue Jhipster-dotnetcore 3.5

### ISSUE THREAD

**Issue by 123445666** [jhipster/jhipster-dotnetcore#1033]
I have an issue with generated project Blazor with jhipster-dotnetcore newest version.
Does anyone have the same or only me ?

##### **Overview of the issue**

Cannot run with Blazor. Stuck at loading page.
Console showing this error:
blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
![Screenshot_1](https://user-images.githubusercontent.com/4284170/168689962-3ca8baca-9a28-40c9-b57e-5136e162ea19.jpg)

##### **Motivation for or Use Case**

Tested ok with jhipster-dotnetcore 3.4 

##### **Reproduce the error**

Used : sample\ jwt-with-blazor-app\ .yo-rc.json

##### **Browsers and Operating System**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by 123445666** [comment]
I think should change 
builder.Services.AddSingleton<AuthenticationStateProvider, AuthenticationService>();
to 
builder.Services.AddScoped<AuthenticationStateProvider, AuthenticationService>();

**Comment by nicolas63** [comment]
oh yes i think it's good solution can you try it ? i think it's due to version update during 3.5
