### ISSUE TITLE
Blazor generated project - User Manager doesn't show - jhipster-dotnetcore 3.4

### ISSUE THREAD

**Issue by 123445666** [jhipster/jhipster-dotnetcore#1034]
##### **Overview of the issue**
![Screenshot_2](https://user-images.githubusercontent.com/4284170/168691151-ae824c77-d2d0-429e-8166-8b43e3b3fcb2.jpg)
Something wrong with /api/users but it's still ok with angular.

##### **Reproduce the error**

Jhipster-dotnetcore 3.4
jhipster 7.8.1
File used: : sample\ jwt-with-blazor-app\ .yo-rc.json

##### **Browsers and Operating System**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by nicolas63** [comment]
this error appear with 3.5 ? if not maybe it's due to https://github.com/jhipster/jhipster-dotnetcore/commit/188f2f4bef969e012beeb9cb0b1537211f8f5869#diff-16ba46caac0a82e2047039a413e7b09bb2f5ccd78c0eb3fba6eecc4293e97519 
In v7 migration the users url has changed

**Comment by 123445666** [comment]
> this error appear with 3.5 ? if not maybe it's due to https://github.com/jhipster/jhipster-dotnetcore/commit/188f2f4bef969e012beeb9cb0b1537211f8f5869#diff-16ba46caac0a82e2047039a413e7b09bb2f5ccd78c0eb3fba6eecc4293e97519 
> 
> In v7 migration the users url has changed

I've just submit a pull request for these issues. Please review it when you have time. Thank you 😁
