### ISSUE TITLE
Something wrong after generated with jdl (Can't generate the custom name of relationships One-One)

### ISSUE THREAD

**Issue by 123445666** [jhipster/jhipster-dotnetcore#1043]
Hi,
I'm using Jhipster for my project but it has something wrong with the generated project.

**The entity:** 
![image](https://user-images.githubusercontent.com/4284170/170885341-589d9f4a-1744-4f11-a86f-c0cb89bdadea.png)
**And the generated Entity  :**
![image](https://user-images.githubusercontent.com/4284170/170885372-200de3f4-aed1-4789-b8b6-88861e68b406.png)

**Expected Result:**
![image](https://user-images.githubusercontent.com/4284170/170885454-e69aa39f-4910-4fcd-8f6e-c6b3e6a8123a.png)

User Entity has Id type String but generated to long? in DTO
##### **Overview of the issue**
All relationship with others name will be the same if 

##### **Motivation for or Use Case**
I want to add multi User in one entity like CreatorId, OwnerId.

##### **Reproduce the error**
Entites
`entity FileContainer {
	Name String,
    ConcurrencyStamp String,
    Creator String,
}

entity FilePart {
	Name String,
    Content String,
    ConcurrencyStamp String,
    
}

relationship OneToOne {
	FileContainer{creator} to User
}

relationship OneToOne {
	FileContainer{owner} to User
}`

##### **JHipster Version(s)**
@nicolas63 @ivanmonteiro  Do you think it's an issue ?
I think should using the name of relationship and add "Id" behind.

##### **JHipster configuration**
jhipster 7.8.1
jhipster-dotnetcore 3.6.0

##### **Browsers and Operating System**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by nicolas63** [comment]
Can you check the behavior of the jhipster (java) generator ?

**Comment by 123445666** [comment]
> Can you check the behavior of the jhipster (java) generator ?

Yes, I've checked with java version. They generate only the Objects. 
![image](https://user-images.githubusercontent.com/4284170/171387903-22e05582-9ea7-4210-9c8d-ac8b74289de6.png)

**Comment by nicolas63** [comment]
we just need to remove related to the user in entity.ejs here (https://github.com/jhipster/jhipster-dotnetcore/blob/main/generators/entity-server/templates/dotnetcore/src/Project.Domain/Entities/Entity.cs.ejs#L75)

**Comment by A-5ingh** [comment]
@nicolas63 removing the `Id` from the listed file will fix the issue? I can also this up.

**Comment by nicolas63** [comment]
No we just need to remove the particular condition for the user entity. (Line 75 )

**Comment by A-5ingh** [comment]
I have tried removing the condition but then it creates duplicate variable with same name but different type with the given entities.
