### ISSUE TITLE
DTO with relationship to User generates UserId as `long?`

### ISSUE THREAD

**Issue by pasikokko** [jhipster/jhipster-dotnetcore#1070]
https://github.com/jhipster/jhipster-dotnetcore/blob/5844d760d11d8f91d5c27def5942fa3aa25811ac/generators/entity-server/templates/dotnetcore/src/Project.Dto/Dto.cs.ejs#L60

I have an entity with one to one relation to User, to extend properties of a User. Generated DTO has UserID of type `long?`, which should be `string`. There will be runtime error, compiler doesn't warn about this mapping error.

**Comment by nicolas63** [comment]
oh yes i think we need to add something like this https://github.com/jhipster/jhipster-dotnetcore/blob/5844d760d11d8f91d5c27def5942fa3aa25811ac/generators/entity-server/templates/dotnetcore/src/Project.Domain/Entities/Entity.cs.ejs#L75

**Comment by nicolas63** [comment]
i think is a regression du to https://github.com/jhipster/jhipster-dotnetcore/commit/020080ea4716497b48fc450cbc53ba64c489e3e8
Can you help us to fix them ?

**Comment by nicolas63** [comment]
i don't reproduce this bug
