### ISSUE TITLE
Missing install phase in app submobule

### ISSUE THREAD

**Issue by nicolas63** [jhipster/jhipster-dotnetcore#1131]
##### **Overview of the issue**

in the https://github.com/jhipster/jhipster-dotnetcore/blob/main/generators/app/index.js the install phase is missing 

##### **Motivation for or Use Case**

During install phase we attempt to init git folder 

##### **Related issues**

This fix this issue (#840)

##### **Suggest a Fix**

add this sections 

```
get install() {
        return super._install();
}
```

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by Shyamala7** [comment]
can I take this?

**Comment by nicolas63** [comment]
Yes sure

**Comment by nicolas63** [comment]
unassigned due to invalid PR

**Comment by tlegrand54** [comment]
Hello, can you assign me this ?

**Comment by nicolas63** [comment]
hello, done

**Comment by nicolas63** [comment]
Fix by #1216
