### ISSUE TITLE
Update MongoDb doc 

### ISSUE THREAD

**Issue by nicolas63** [jhipster/jhipster-dotnetcore#1132]
##### **Overview of the feature request**

After this PR #1123  user and account are managed by mongoDB so we can update this page (https://jhipsternet.readthedocs.io/en/latest/Features/mongodb.html) to supress the WIP part 

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by vedant-z** [comment]
Hey @nicolas63 in this issue basically the WIP part needs to be removed right ?

I would like to work on this as well

**Comment by nicolas63** [comment]
> Hey @nicolas63 in this issue basically the WIP part needs to be removed right ?
> 
> I would like to work on this as well

yes we just need to remove WIP part
