### ISSUE TITLE
Enable sonar only on default app

### ISSUE THREAD

**Issue by nicolas63** [jhipster/jhipster-dotnetcore#1133]
##### **Overview of the issue**

Here we enable sonar analysis on default app and also in cqrs app 

https://github.com/jhipster/jhipster-dotnetcore/blob/main/test-integration/scripts/01-init-env.sh#L21
https://github.com/jhipster/jhipster-dotnetcore/blob/main/test-integration/scripts/01-init-env.sh#L25

we have only default app declared on sonar cloud 
https://sonarcloud.io/project/overview?id=jhipster_jhipster-sample-app-blazor
https://sonarcloud.io/project/overview?id=jhipster_jhipster-sample-app-dotnetcore

so today cqrs scan replace default app scan 

##### **Suggest a Fix**

we can remove the cqrs app from this lines 
https://github.com/jhipster/jhipster-dotnetcore/blob/main/test-integration/scripts/01-init-env.sh#L21
https://github.com/jhipster/jhipster-dotnetcore/blob/main/test-integration/scripts/01-init-env.sh#L25

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by A-5ingh** [comment]
Hey @nicolas63, hope you are doing well! Can you please assign this issue to me?

**Comment by nicolas63** [comment]
Yes sure

**Comment by A-5ingh** [comment]
@nicolas63 can you please review once you get time.
