### ISSUE TITLE
Rework priorities to use const

### ISSUE THREAD

**Issue by nicolas63** [jhipster/jhipster-dotnetcore#1135]
##### **Overview of the feature request**

Since this rfc (https://github.com/jhipster/generator-jhipster/blob/main/rfcs/3-jhipster-rfc-unambiguous-priorities.md) the generator-jhipster use constants for priorities and we can also use it in this generator 

So we need to rework all priorities write like this : 

```
 get initializing() {
    return {
      initializingTask() {
        this._sayHello();
      }
    }
  }
```

by 

```
get [INITIALIZING_PRIORITY]() {
    return {
      initializingTask() {
        this.sayHello();
      }
    }
  }
```

##### **Motivation for or Use Case**

the old way was not support in jhipster v8 

##### **Related issues or PR**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by vedant-z** [comment]
@nicolas63 I would like to work on this

**Comment by nicolas63** [comment]
nice, i have assign to you
