### ISSUE TITLE
AuditedEntityBase improvment 

### ISSUE THREAD

**Issue by nicolas63** [jhipster/jhipster-dotnetcore#1137]
##### **Overview of the feature request**

As discuss in gitter ( https://gitter.im/JHipster-NET/jhipster-dotnetcore) today our AuditedEntityBase don't inherite from 
https://github.com/jhipster/jhipster-dotnetcore/blob/main/generators/server/templates/dotnetcore/src/Project.Domain/Entities/BaseEntity.cs.ejs

We just need to inherite from BaseEntity in AuditedEntityBase to get the identity

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by aswarthm** [comment]
Hey, I'd like to work in this. From your description and gitter, I believe that the AuditedEntityBase should inherit from BaseEntity. i.e "public abstract class AuditedEntityBase : BaseEntity". Am I right?

**Comment by nicolas63** [comment]
> Hey, I'd like to work in this. From your description and gitter, I believe that the AuditedEntityBase should inherit from BaseEntity. i.e "public abstract class AuditedEntityBase : BaseEntity". Am I right?

Yes you are right

**Comment by aswarthm** [comment]
Thank you, I will PR this during October

**Comment by nicolas63** [comment]
fixed by #1156
