### ISSUE TITLE
Update copyright date 

### ISSUE THREAD

**Issue by nicolas63** [jhipster/jhipster-dotnetcore#1138]
##### **Overview of the issue**

The copyright is date is 2019-2021 we need to update to 2022
like here : (https://github.com/jhipster/jhipster-dotnetcore/blob/main/generators/app/prompts.js#L2)

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by Indrajeet-S** [comment]
I would like top change this

**Comment by Indrajeet-S** [comment]
Hey, so I have to change "2019-2021" to "2019-2022" in all files right?
and I have to make this PR after 1 October an
could you assign me with some more issues

**Comment by nicolas63** [comment]
> Hey, so I have to change "2019-2021" to "2019-2022" in all files right? 

yes

> could you assign me with some more issues

add a comment on the issues that interest you

**Comment by Indrajeet-S** [comment]
okay... I will do.. thanks

**Comment by Indrajeet-S** [comment]
@nicolas63

**Comment by nicolas63** [comment]
Closed by #1151
