### ISSUE TITLE
SonarCloud analysis on generated app, and on PR 

### ISSUE THREAD

**Issue by nicolas63** [jhipster/jhipster-dotnetcore#114]
@deepu105, @pascalgrimaud or @jdubois can you create the project https://github.com/jhipster/jhipster-sample-app-dotnetcore on sonarcloud please ? 

The SonarCloud app(bot) is also link to github but analysis is done only on branch like https://github.com/jhipster/jhipster-dotnetcore/pull/111 
I think the feature is good for monitoring code quality 
Can you verify the configuration and check if you can activate this feature on all PR ?

**Comment by pascalgrimaud** [comment]
@nicolas63 : ok I will do it tomorrow. If I forget, don't hesitate to remind me :)

**Comment by nicolas63** [comment]
@pascalgrimaud just a quick reminder 😃

**Comment by pascalgrimaud** [comment]
@nicolas63 : just done, right now
- project key: jhipster_jhipster-sample-app-dotnetcore
- organization key: jhipster

I added the SONAR_TOKEN to GitHub secrets.
The analyze will be there: https://sonarcloud.io/project/configuration?id=jhipster_jhipster-sample-app-dotnetcore

Don't hesitate to tell me if it doesn't work

**Comment by nicolas63** [comment]
@pascalgrimaud thank you very much. Have you verify the second question for sonarcloud bot ? 
For now only internal PR was analyse by the SonarCloud bot (like #111)

![image](https://user-images.githubusercontent.com/14818936/79796997-cc864880-8356-11ea-81c4-fe724121d5d8.png)

if it is possible i would like analyse also the PR from fork repository

**Comment by nicolas63** [comment]
I think the configuration needs to be done here, but I don't have the rights.  
https://github.com/apps/sonarcloud/installations/5508828

**Comment by pascalgrimaud** [comment]
for security reason, I never manage to make it work for PR, as all secrets are not available for PRs
It can only works for local branch

Would you like to activate it ? it means you'll have to work with local branch of this repo, but the bad things is it will trigger 2 builds: one for branch, one for PR

**Comment by nicolas63** [comment]
Oh ok, it's already activate on local branch. Thank you for the explanation

**Comment by nicolas63** [comment]
@pascalgrimaud, I reopen this issue. I think we misunderstood, I would only the PR decoration with sonarcloud. It seems possible like (https://github.com/microsoft/VoTT/pull/938) and is it document here ( https://sonarcloud.io/documentation/analysis/pull-request/)

**Comment by pascalgrimaud** [comment]
Indeed, I think we don't understand well each other, as it seems to be differents things here.

Analyze of blueprint **jhipster-dotnetcore**
- https://github.com/jhipster/jhipster-dotnetcore -> https://sonarcloud.io/dashboard?id=jhipster-core
- the automatic analysis is disabled, so we need to put a SONAR_TOKEN in secrets and push the analyze with the CI
- this part is done today

Analyze of the another project **jhipster/jhipster-sample-app-dotnetcore**
- https://github.com/jhipster/jhipster-sample-app-dotnetcore -> https://sonarcloud.io/dashboard?id=jhipster_jhipster-sample-app-dotnetcore
- I put a SONAR_TOKEN in secrets
- the analyze needs to be done by the CI -> not done today because no CI

Analyze of a generated project
- there can be a conflict with the previous item
- I don't see the CI part for a generated project: https://github.com/jhipster/jhipster-dotnetcore/blob/master/.github/workflows/test-integration-jwt.yml#L47-L54
- maybe something similar to https://github.com/jhipster/generator-jhipster/blob/master/test-integration/scripts/25-sonar-analyze.sh

But for this part, it's a little bit more complex, as I said, I'm not sure it's doable, as we change the settings to "manual" instead of "automatic" and it used the SONAR_TOKEN.
If I understand well the documentation from SonarCloud about PR, we need to set it to "automatic":
- the user opened a PR
- it will launch a webhook to SonarCloud
- SonarCloud will get the project and analyze it

Don't hesitate to tell me if I'm wrong, or point me examples, documentation etc, if you find some of them.

**Comment by nicolas63** [comment]
Analyze of blueprint jhipster-dotnetcore : this part is done today 
Analyze of the another project jhipster/jhipster-sample-app-dotnetcore : sonar project created and yes I have to add the CI and i think use something like https://github.com/jhipster/generator-jhipster/blob/master/test-integration/scripts/25-sonar-analyze.sh

The last part is PR decoration by sonarcloud bot in generator project not in generated (https://github.com/apps/sonarcloud) : done only on local branch but seems possible on PR from fork 

an exemple from PR with local branch : #111 

![image](https://user-images.githubusercontent.com/14818936/79796997-cc864880-8356-11ea-81c4-fe724121d5d8.png)

but i'm looking into the sonarcloud projects and many projects use PR decoration : a PR exemple 
(https://github.com/microsoft/VoTT/pull/938) and is it document here ( https://sonarcloud.io/documentation/analysis/pull-request/)


In SonarCloud the documentation says  : 

```
PR Decoration

This section details how to decorate your PRs with SonarCloud issues in your SCM provider's interface.
Specifying Your PR Provider

Specify your PR provider in your global settings at Administration > General Settings > Pull Requests > General > Provider. This is the name of the system managing your PR. When using the SonarCloud Extension for Azure DevOps Services, the provider is automatically populated. It's the same for GitHub if you are using the Travis CI Add-on and Bitbucket Cloud if you are building with Bitbucket Pipelines.
GitHub PR Decoration

To add PR decoration to Checks on GitHub, you need to update your project-level settings.
Updating Your GitHub Project Settings

In your project settings, set your project repository identifier (for example, SonarSource/sonarcloud) at Administration > General Settings > Pull Requests > Integration with GitHub > Repository identifier.
```

**Comment by pascalgrimaud** [comment]
I tried to param it, everything should be config as mentionned in docs but still doesn't work :(

https://sonarcloud.io/project/settings?category=pull_request&id=jhipster_jhipster-dotnetcore

**Comment by nicolas63** [comment]
I don't understand why this isn't working. Maybe you can give me the rights temporarily? 
Thanks again for your time on this issue

**Comment by pascalgrimaud** [comment]
did you link your GitHub account to SonarCloud @nicolas63 ?

**Comment by nicolas63** [comment]
yes

**Comment by pascalgrimaud** [comment]
can you contact me by private mail plz ?

**Comment by pascalgrimaud** [comment]
Oh, I just look at the logs in GitHub Actions:
- https://github.com/jhipster/jhipster-dotnetcore/pull/138/checks?check_run_id=605919815
- see the stacktrace:

```
INFO: SCM collecting changed files in the branch (done) | time=3226ms
INFO: Indexing files...
INFO: Project configuration:
INFO:   Excluded sources: node_modules/**
INFO: Load project repositories
INFO: ------------------------------------------------------------------------
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
INFO: Total time: 32.676s
ERROR: Error during SonarQube Scanner execution
INFO: Final Memory: 19M/67M
ERROR: You're not authorized to run analysis. Please contact the project administrator.
ERROR: 
INFO: ------------------------------------------------------------------------
ERROR: Re-run SonarQube Scanner using the -X switch to enable full debug logging.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! generator-jhipster-dotnetcore@0.3.0 sonar:scanner: `sonar-scanner`
```

That's because the SONAR_TOKEN is not available for manual analyze, maybe ?

**Comment by nicolas63** [comment]
Yes, it's work now 😃

**Comment by nicolas63** [comment]
All works now, analysis on generated app, and on PR. 
Great thanks to @pascalgrimaud
