### ISSUE TITLE
Rework Prerequisites

### ISSUE THREAD

**Issue by nicolas63** [jhipster/jhipster-dotnetcore#1165]
##### **Overview of the feature request**

In Prerequisites we have a link to the jhipster documentation with lot of information and in fact we just need to ask to install jhipster like this 
```
npm install -g generator-jhipster
```

rework is needed here : 
https://github.com/jhipster/jhipster-dotnetcore/blob/main/docs/Introduction/getting-started.md#prerequisites

and here 
https://github.com/jhipster/jhipster-dotnetcore#prerequisites

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by tlegrand54** [comment]
Can I help with this?

**Comment by nicolas63** [comment]
Yes, i have assigned you
