### ISSUE TITLE
Remove running-local-blueprint-version-for-development part in readme

### ISSUE THREAD

**Issue by nicolas63** [jhipster/jhipster-dotnetcore#1166]
##### **Overview of the feature request**

the https://github.com/jhipster/jhipster-dotnetcore#running-local-blueprint-version-for-development is not needed here because it's too complex for the readme and this documentation is already here https://jhipsternet.readthedocs.io/en/latest/Development/RunLocal.html

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by tlegrand54** [comment]
Can I help you with this?

**Comment by nicolas63** [comment]
Yes, i have assigned you

**Comment by tlegrand54** [comment]
Hi, Nicolas, 
I just created the pull request #1181 but I don't know how to link it with this issue

**Comment by nicolas63** [comment]
I have linked the issue, the best think to do is to mention the issue in the comment of your pull request like this 'fix #issuenumber'
