### ISSUE TITLE
Fix Heroku deploy docs 

### ISSUE THREAD

**Issue by ivanmonteiro** [jhipster/jhipster-dotnetcore#1177]
##### **Overview of the issue**

Heroku as announced that free dynos and resoures will not be available anymore

Update the docs: 
Remove mention about free dynos/resources and make it clear that a paid plan is required

The docs file is here:
https://github.com/jhipster/jhipster-dotnetcore/blob/main/docs/Features/heroku.md

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by nicolas63** [comment]
Good idea, it's also discuss here https://github.com/jhipster/generator-jhipster/issues/19551

**Comment by prokan468** [comment]
Hi, please do assign this issue to me.

**Comment by nicolas63** [comment]
Sure, i have assigned you

**Comment by prokan468** [comment]
#1182 Hi, I have updated the Heroku Documentation. Please do  accept the PR.
