### ISSUE TITLE
Follow Microsoft's naming guidelines

### ISSUE THREAD

**Issue by kbeaugrand** [jhipster/jhipster-dotnetcore#1207]
##### **Overview of the feature request**

The objective of this issue is to follow the .NET Standards naming conventions.
Naming rules are set on the .editorconfig file of the bluepring (see [Code-Style naming rules](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/naming-rules?WT.mc_id=AZ-MVP-5004641))

##### **Motivation for or Use Case**

Naming conventions on the blueprint doesn't follows the standards.
Some guidelines are present on [Naming guidelines](https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/naming-guidelines?WT.mc_id=AZ-MVP-5004641) page.

Please note that suggestions below are not exhaustive.

##### **Related issues or PR**

- [ ] internal and private field should not have "_" prefix
- [ ] static fields should not have "s_" prefix

**Comment by nicolas63** [comment]
Sorry, but this page https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/naming-guidelines?WT.mc_id=AZ-MVP-5004641 talks about public field. For the private field, this one explains how to name them https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions. And these rules are applied by the runtime and the sdk (https://github.com/dotnet/runtime/blob/main/.editorconfig)

**Comment by kbeaugrand** [comment]
My bad I didn't read correctly these pages...
Even I dislike those rules, you're completely right!

Thanks for the feedback
