### ISSUE TITLE
Update to the latest version of setup-dotnet in our github actions

### ISSUE THREAD

**Issue by nicolas63** [jhipster/jhipster-dotnetcore#1210]
##### **Overview of the issue**

Since few week multiple job randomly failed due to this issue

##### **Suggest a Fix**

we are at version 1 and we need to upgrade to version 3 in these files : 

https://github.com/jhipster/jhipster-dotnetcore/blob/main/.github/workflows/test-integration-jwt.yml
https://github.com/jhipster/jhipster-dotnetcore/blob/main/.github/workflows/test-integration-microservice.yml
https://github.com/jhipster/jhipster-dotnetcore/blob/main/.github/workflows/test-integration-oauth.yml

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by tlegrand54** [comment]
Hello, can i do it ?

**Comment by nicolas63** [comment]
yes

**Comment by tlegrand54** [comment]
Hey, when you said "we are at version 1 and we need to upgrade to version 3 in these files", do you mean the version of  actions/setup-dotnet?

**Comment by nicolas63** [comment]
Yes exactly

**Comment by nicolas63** [comment]
Fix by #1215
