### ISSUE TITLE
Upgrade to .NET 7 

### ISSUE THREAD

**Issue by ivanmonteiro** [jhipster/jhipster-dotnetcore#1223]
##### **Overview of the feature request**

.NET 7 will be released soon and it would be nice to upgrade the project to use .Net v7

##### **Related issues or PR**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by tlegrand54** [comment]
Hello, if it possible can I help you on this ?

**Comment by nicolas63** [comment]
Yes if @ivanmonteiro doesn't work on it. If it's ok you can start here https://github.com/jhipster/jhipster-dotnetcore/blob/main/generators/server/templates/dotnetcore/src/Directory.Packages.props

To update the dependencies. We also need to update docker image version. And apply all new good practices.

**Comment by ivanmonteiro** [comment]
> Hello, if it possible can I help you on this ?

Yes, of course you can help. Also don't be afraid to ask questions

**Comment by tlegrand54** [comment]
No problem, thanks a lot

**Comment by tlegrand54** [comment]
I have a question, how can I test after I change the version of .NET?

**Comment by nicolas63** [comment]
You can run 
```npm link```
After that your local version is used when you run 
```
jhipster --blueprints dotnetcore
```

If you want debug the generator you can use vs code with f5 and if you want you can change the generated folder here  (https://github.com/jhipster/jhipster-dotnetcore/blob/main/.vscode/launch.json)

**Comment by tlegrand54** [comment]
Hello, sorry to give you a feedback now.
I change all csproj with net7.0 but I can't use the F5 or the command jhipster --blueprints dotnetcore to be sure all is ok. 
I have the following mistake 

![image](https://user-images.githubusercontent.com/20354112/206895587-15ad00a1-890b-4ab4-99ef-a591361d96d7.png)

**Comment by ivanmonteiro** [comment]
> Hello, sorry to give you a feedback now. I change all csproj with net7.0 but I can't use the F5 or the command jhipster --blueprints dotnetcore to be sure all is ok. I have the following mistake
> 
> ![image](https://user-images.githubusercontent.com/20354112/206895587-15ad00a1-890b-4ab4-99ef-a591361d96d7.png)

It's hard to tell without knowing what changes you made. Do you have a fork, PR or branch with the changes you made?

**Comment by tlegrand54** [comment]
Hello @ivanmonteiro , I just update my fork [tlegrand54:1210_update_version_dotnet](https://github.com/tlegrand54/jhipster-dotnetcore/tree/1210_update_version_dotnet)

**Comment by ivanmonteiro** [comment]
> Hello @ivanmonteiro , I just update my fork [tlegrand54:1210_update_version_dotnet](https://github.com/tlegrand54/jhipster-dotnetcore/tree/1210_update_version_dotnet)

The only thing I can think of is the version of generator-jhipster you're using. Sometimes we see errors If we're using a newer version than the one at package.json of jhipster.net 
https://github.com/jhipster/jhipster-dotnetcore/blob/fb50df3624c20e3a1d71dc4f07004889c845670f/package.json#L29

**Comment by ivanmonteiro** [comment]
Run `jhipster --version` and check if the main jhipster version matches with the one above.

Also make sure that you linked generator-jhipster-dotnetcore from your fork's folder:
 https://github.com/jhipster/jhipster-dotnetcore/blob/fb50df3624c20e3a1d71dc4f07004889c845670f/CONTRIBUTING.md?plain=1#L207

Also run `npm install` inside your fork's folder to install any missing packages and let me know if it's working now.

**Comment by tlegrand54** [comment]
Hello @ivanmonteiro, sorry for a long time without some news. 
So my version of Jhipster is 7.8.1 and  I always have the same issue when I try to generate a new app.

**Comment by nicolas63** [comment]
Hello, @tlegrand54 i think you have a problem with the node version like this issue (https://github.com/jhipster/jhipster-dotnetcore/issues/1234)

**Comment by tlegrand54** [comment]
Hello @nicolas63, that is my issue, I downgrade to node 16 and that works

**Comment by 123445666** [comment]
I saw this task was not updated since 1 month ago so I have some updates for it.
