### ISSUE TITLE
Path Not Exported error 

### ISSUE THREAD

**Issue by Rummy99** [jhipster/jhipster-dotnetcore#1234]
Hi,

I am getting below path not exported error while creating jhipster dotnetcore blueprint. Please advice how to fix it.

**ERROR! Package subpath './generators/app' is not defined by "exports"**

![PXL_20221110_021116545.jpg](https://user-images.githubusercontent.com/85660159/200983878-0690227f-7c27-4365-a50f-e62447b99a23.jpg)

**Comment by tristanblc** [comment]
Hello,
In order to fix that, try to change "exports" in the file "\node_modules\generator-jhipster-dotnetcore\node_modules\generator-jhipster\package.json".
 ```
   "exports": {
    ".": {
      "import": "./lib/index.mjs",
      "default": "./lib/index.js"
    },
    "./cli/*": "./cli/*",
    "./generators/*": "./generators/*/index.js",
    "./generators/client/*" :"./generators/client/index.js",
    "./generators/generator-list": "./generators/generator-list.js", 
    "./generators/utils": "./generators/utils.js",
    "./generators/generator-constants" : "./generators/generator-constants.js",
    "./generators/needle-base" : "./generators/needle-base.js",
    "./jdl/": "./jdl/",
    "./lib/": "./lib/",
    "./utils/": "./utils/",
    "./package.json": "./package.json",
    "./esm/cli": "./cli/index.mjs",
    "./esm/generators/*": "./generators/*/esm.mjs",
    "./esm/generators": "./lib/constants/generators.mjs",
    "./esm/priorities": "./lib/constants/priorities.mjs",
    "./esm/support": "./lib/support/index.cjs"
  },
 ```

**Comment by nicolas63** [comment]
thanks @tristanblc you have right, today the blueprint do not support node 18 @Rummy99 can you try with node 16 ?
