### ISSUE TITLE
Jhipster Dotnet Configuration issue

### ISSUE THREAD

**Issue by ajmerchand88** [jhipster/jhipster-dotnetcore#1249]
Hi All,

I am facing issue with the dotnet app installation using docker. Here is the issue i am facing right now. Can anyone please help me solve this problem??

--------------------------------------------------------------------------------------------------------------------------------------------------------------

ERROR! fatal: detected dubious ownership in repository at '/home/jhipster/app'
To add an exception for this directory, call:

        git config --global --add safe.directory /home/jhipster/app

**Comment by nicolas63** [comment]
hello, sorry for the long delay. Have you try the command ? can you give me the .yo-rc.json ?
