### ISSUE TITLE
Release v1.0.0

### ISSUE THREAD

**Issue by nicolas63** [jhipster/jhipster-dotnetcore#127]
@jdubois, @deepu105 and @pascalgrimaud i think this project is nearly ready for the first release.
I think we can release this version just after jhipster v6.9.0.

Are you agree @danielpetisme ? 

A lot of work has been done since 0.3 (https://github.com/jhipster/jhipster-dotnetcore/milestone/1)

Have you some requirement in terms of features or documentation for blueprint release ?

**Comment by danielpetisme** [comment]
You did an awesome job Nicolas!!
I've got 2 main conditions to hit 1.0,0.
Feature side, it looks like we cover the `sample-app` scenario (client/server generation + JWT auth + entities generation with data migration + the corresponding tests). Can you confirm that.

The other aspect is the project overall quality, you did a great job with sonar (either for the generator and for the generated application). I have mixed feeling regarding documentation, if I ask a new team to start with the generator, do you think we have all the information to generate a first app without issue? All the documentation relies on the `README.md` right? Is it enough?

Again THANK YOU!!!

**Comment by nicolas63** [comment]
```
(client/server generation + JWT auth + entities generation with data migration + the corresponding tests). Can you confirm that.
```
Yes, just the data migration was done by entity framework not by the generator 

```
The other aspect is the project overall quality
```
https://sonarcloud.io/organizations/jhipster/projects i'am work on it, i juste have to exclude rules like main jhipster sample. And publish code coverage. 

 ```if I ask a new team to start with the generator, do you think we have all the information to generate a first app without issue? All the documentation relies on the README.md right? Is it enough? ```

Yes, all documentation was done on the readme, i can complete it and i think is good. 
Maybe we can publish a v1.0.0-alpha and if the documentation is a problem we can choose another way to document the generator

@danielpetisme what do you think ?

**Comment by nicolas63** [comment]
After exclude generated files the analysis is not bad 😃 , now i try to add coverage 

![image](https://user-images.githubusercontent.com/14818936/79961088-80d2bc80-8486-11ea-808c-6aab663be7d7.png)

**Comment by danielpetisme** [comment]
@nicolas63 you rock. I do approve the v1.0.0

**Comment by jdubois** [comment]
Don't forget to announce it everywhere!! Can you tell me when I can tweet this with the JHipster account? Or just @ mention me

**Comment by nicolas63** [comment]
@jdubois can you tweet release 1.0.0-alpha of this package ? 
Here is a summary of the features brought by this version : 
 - OpenIdConnect (With keycloak and okta) 
 - The react support 
 - Sonar improvement 
 - Many bug fixes 

The link of the release note (https://github.com/jhipster/jhipster-dotnetcore/releases) 

Thank you in advance !

**Comment by jdubois** [comment]
Thanks, doing it right now! @nicolas63 are you on Twitter? What's your handle?

**Comment by nicolas63** [comment]
No, sorry i'm not on twitter

**Comment by nicolas63** [comment]
thanks @jdubois
