### ISSUE TITLE
node version conflict FATAL error

### ISSUE THREAD

**Issue by josersleal** [jhipster/jhipster-dotnetcore#1337]
jhipster --version: 8.0.0-beta.2
dotnet 7
running "jhipster --blueprints dotnetcore"

--------------------Node version 16.20.2

Error:
FATAL! You are running Node version 16.20.2
JHipster requires Node version ^18.13.0 || >= 20.2.0
Please update your version of Node.

__________________________________________________________________________________
jhipster --version: 8.0.0-beta.2
running "jhipster --blueprints dotnetcore"
dotnet 7
---------------------Node version  20.2.0

Error:
ERROR! ERROR! Package subpath './generators/app' is not defined by "exports" in /root/.nvm/versions/node/v20.2.0/lib/node_modules/generator-jhipster-dotnetcore/node_modules/generator-jhipster/package.json

There are several errors addressing this but only refer to jhipster < v8 and suggest to downgrade to node v16
when using jhipster v8 the issue is referrred to as fixed. It is not imo.

**Comment by nicolas63** [comment]
Can you retry with node 16 and jhipster 7.8.1 ?

**Comment by nicolas63** [comment]
fix with #1340
