### ISSUE TITLE
Migrate to JHipster v8

### ISSUE THREAD

**Issue by nicolas63** [jhipster/jhipster-dotnetcore#1340]
##### **Overview of the feature request**

According jhipster/generator-jhipster#23449 JHipster v8 is getting close, we should migrate and make sure everything is working correctly.

**Comment by nicolas63** [comment]
Hi @mshima , after some tests I have a strange behavior when I generate a project and run npm install 
After that I get this error when I run jhipster-dotnetcore again. 
```
ERROR! ERROR! Package subpath './generators/entity' is not defined by "exports" in myfolder\node_modules\generator-jhipster-dotnetcore\node_modules\generator-jhipster\package.json
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './generators/entity' is not defined by "exports" in myfolder\node_modules\generator-jhipster-dotnetcore\node_modules\generator-jhipster\package.json
    at new NodeError (node:internal/errors:405:5)
    at exportsNotFound (node:internal/modules/esm/resolve:362:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:698:9)
    at resolveExports (node:internal/modules/cjs/loader:567:36)
    at Module._findPath (node:internal/modules/cjs/loader:636:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1063:27)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (myfolder\node_modules\generator-jhipster-dotnetcore\generators\entity\index.js:2:25) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```
Without npm install I don't get this error

**Comment by mshima** [comment]
@nicolas63 you probably got hit by https://github.com/jhipster/generator-jhipster/issues/24028.
You can workaround by using `—skip-jhipster-dependencies`.

**Comment by nicolas63** [comment]
@mshima who get this bounty ? You ? Me ? Both ?

**Comment by mshima** [comment]
The actual migration happened in https://github.com/jhipster/jhipster-dotnetcore/pull/1358 with 158 commits, I am not sure why this bug was not closed since it had `Fixes https://github.com/jhipster/jhipster-dotnetcore/issues/1340` in the description.
The following PRs documentations and adjusts.
I think split $100 for the review and adjusts $400 for migration and following adjust in my part  is fair.

**Comment by nicolas63** [comment]
totally agree with you, even if this ticket took me a bit of work, you've done most of it and thank you again for that.

**Comment by nicolas63** [comment]
bounty claimed : https://opencollective.com/generator-jhipster/expenses/173885

**Comment by mshima** [comment]
@DanielFran bounty claimed https://opencollective.com/generator-jhipster/expenses/176998

**Comment by DanielFran** [comment]
@mshima approved
