### ISSUE TITLE
Update to dotnet 8 

### ISSUE THREAD

**Issue by nicolas63** [jhipster/jhipster-dotnetcore#1417]
##### **Overview of the feature request**

Dotnet 8 is the new LTS and it is released

##### **Related issues or PR**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by nicolas63** [comment]
@pascalgrimaud can we have a bounty on this issue ?

**Comment by pascalgrimaud** [comment]
done! :)

**Comment by nicolas63** [comment]
Thanks, I'm starting to work on it

**Comment by nicolas63** [comment]
Bounty claimed : https://opencollective.com/generator-jhipster/expenses/175011

**Comment by pascalgrimaud** [comment]
@nicolas63 : approved
