### ISSUE TITLE
Preference for primary key in JDL not respected

### ISSUE THREAD

**Issue by JeSuisAlrick** [jhipster/jhipster-dotnetcore#1428]
##### **Overview of the issue**

Preference for primary key in JDL not respected.

##### **Motivation for or Use Case**

According to the [Add support to custom ids](https://github.com/jhipster/generator-jhipster/pull/13258) I should be able to override the primary field type by doing the following:
```
entity MyEntity {
   id UUID
}
```
##### **Reproduce the error**

1) Using the following JDL, generate a new project:

   ```
   application {
     config {
       baseName MyMS
       applicationType microservice
       packageName my.ms
       authenticationType oauth2
       prodDatabaseType mssql
       blueprints [dotnetcore]
       databaseType sql
       skipClient true
       skipUserManagement true
       enableSwaggerCodegen true
     }
     entities *
   }

   entity MyEntity {
     id UUID
     name String
   }
   ```
   `npx jhipster jdl jhipster-jdl.jdl`

2) Apply the `jhipster-dotnetcore` blueprint: `npx jhipster-dotnetcore`

3) View the domain objects that were generated
    <img width="245" alt="image" src="https://github.com/jhipster/jhipster-dotnetcore/assets/177066/78ac78da-b5fc-4f9c-9409-611030729a8a">

**Expected result:**
The primary key should be of type Guid.

**Actual result**
Primary key is of type long

##### **JHipster Version(s)**

8

##### **JHipster configuration**

[.yo-rc.json](https://github.com/jhipster/jhipster-dotnetcore/files/13619709/yo-rc.json)

  <details>
  <summary>JDL definitions</summary>
  <pre>
   application {
     config {
       baseName MyMS
       applicationType microservice
       packageName my.ms
       authenticationType oauth2
       prodDatabaseType mssql
       blueprints [dotnetcore]
       databaseType sql
       skipClient true
       skipUserManagement true
       enableSwaggerCodegen true
     }
     entities *
   }

   entity MyEntity {
     id UUID
     name String
   }
  </pre>
  </details>

##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by nicolas63** [comment]
It's exact today the uuid type is not map to guid in c# maybe we can add this type. Can you help us ? The mapping code is here https://github.com/jhipster/jhipster-dotnetcore/blob/main/generators/bootstrap-application/support/utils.js#L20

**Comment by JeSuisAlrick** [comment]
@nicolas63 I've started a PR here: https://github.com/jhipster/jhipster-dotnetcore/pull/1430

I'll continue in the week.

**Comment by JeSuisAlrick** [comment]
@nicolas63 having trouble with some of the integration tests. Can you take a look and provide any feedback?

**Comment by nicolas63** [comment]
Close by #1430
