### ISSUE TITLE
When will this repo upgraded to the lates jhipster version?

### ISSUE THREAD

**Issue by Puresoft** [jhipster/jhipster-dotnetcore#1493]
##### **Overview of the issue**

When will this repo upgraded to the lates jhipster version?

##### **Motivation for or Use Case**

I'm wondering if this repo is still under active development, there are many open issues unanswered.

##### **JHipster Version(s)**
"generator-jhipster": "8.6.0",
"generator-jhipster-dotnetcore": "^4.1.0"

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by zahasoftware** [comment]
I was thinking the same thing because of the IA. But it is an assumption

**Comment by DanielFran** [comment]
Fixed by https://github.com/jhipster/jhipster-dotnetcore/pull/1526
