### ISSUE TITLE
Enum support 

### ISSUE THREAD

**Issue by nicolas63** [jhipster/jhipster-dotnetcore#152]
For now the enum type is no support

**Comment by ivanmonteiro** [comment]
I'm doing some development on enum on my fork at the add-enum branch and hope to push a PR soon

**Comment by ivanmonteiro** [comment]
Just adding a remark that without the server-side translations (see issue #252), the client app will display translation-not-found error.

**Comment by ivanmonteiro** [comment]
Bounty claimed https://opencollective.com/generator-jhipster/expenses/21333
