### ISSUE TITLE
Why you configured Dependabot Preview to automatically update dependencies? Is it a good practice?

### ISSUE THREAD

**Issue by maznag** [jhipster/jhipster-dotnetcore#175]
Why you configured Dependabot Preview to automatically update dependencies? Is it a good practice?

I think we need to update manually the versions to avoid regressions.

**Comment by nicolas63** [comment]
I think integration test are sufficient to avoid regressions and I merge PR of dependabot manually. But we can discuss if you are desagree

**Comment by maznag** [comment]
Sorry for the delay !

I think it's better to do it manually like for the main Jhipster generator. I find that there is too much PR. 128 PR while we are just at version 0.3.0

I'll let you decide what's the best approach.

**Comment by nicolas63** [comment]
An other solution is to create dependabot PR on other branch and merge it manually after many update. 
What do you think about it ?

**Comment by maznag** [comment]
Why not, but we need to rebase before merge

**Comment by nicolas63** [comment]
Yes, I'll do that.  I see you regularly on the project would you be interested to come in the jhipster.net developers team ?

**Comment by maznag** [comment]
Interesting. Yes I would like to join the JHipster.net developers team. Thanks for your proposition. I'm starting to get interested in dotnet core and I intend to contribute more to this project. I'm also a generator-jhipster (java/Angular) contributor (11 commit https://github.com/jhipster/generator-jhipster/commits?author=maznag  and I want to participate also this year).

**Comment by nicolas63** [comment]
done in (https://github.com/jhipster/jhipster-dotnetcore/commit/9d69482d4cb8e4ef1bcd37b0e974f89634489212)
