### ISSUE TITLE
Add sort possibility 

### ISSUE THREAD

**Issue by maznag** [jhipster/jhipster-dotnetcore#176]
Sort doesn't work  for users management.

**Comment by nicolas63** [comment]
Can you analyze the server requests that failed during sorting ?

**Comment by maznag** [comment]
Sort isn't implemented yet ! There is just a Sort class but isn't used in the UsePageable method

```
public static IPage<TEntity> UsePageable<TEntity>(this IQueryable<TEntity> receiver, IPageable pageable)
            where TEntity : class
        {
            var entities = receiver.Skip(pageable.Offset)
                .Take(Math.Min(pageable.PageSize, PageableBinderConfig.DefaultMaxPageSize));
            return new Page<TEntity>(entities.ToList(), pageable, receiver.Count());
        }
```

I find that there is too much unused code for pagination/sort classes.

@danielpetisme Have you used the Spring Data implementation org.springframework.data.domain.Pageable and Sort used in main generator JHipster to implement these classes? It seems to me that it is the same implementation!

Aren't there existing classes in dotnet core to easily implement pagination/sort?

**Comment by danielpetisme** [comment]
You're right I took inspiration from spring pagination and translated it into c# and yes the migration is not done 100%

I searched for the same kind of lib in .Net but I wasn't satisfied.

What I like with spring pagination is the fact of using the same objects across the web and data access layers. The controller catch from the query string a `Pageable` wich is forward as is to the repository method. Then the repository  returns a `Page` which is forwarded to the client as the controller response object. Everything is glued together in a consistent approach 

When I looked at the .Net ecosystem I found either libs to deserialize request parameters ,(and very static) or enhancing the EF queries to do DB pagination but I still would have to write code to link everything together.

If you think there is a better way, a more c# idiomatic solution or even better libs that cover the same scope, feel free to replace it! It won't hurt my feelings 😁

Cheers

**Comment by maznag** [comment]
@danielpetisme  thanks for these precisions.

Likewise, I couldn't find a satisfied generic implementation. I only find simple examples for specific cases.

I find what you have initiated is in the right direction. I will try to continue on your work by adding a Sort possibility.
