### ISSUE TITLE
Main generator-jhipster generate too much unused components for ClientApp

### ISSUE THREAD

**Issue by maznag** [jhipster/jhipster-dotnetcore#199]
Main generator-jhipster generate too much unused component for ClientApp such as: audits, configuration, docs, health and metrics. there is non backend for these components.

We need to remove these component during the generation process.

**Comment by pascalgrimaud** [comment]
@maznag : for your information, we plan to remove all these components, probably in the next major v7 version of generator-jhipster.
All these information will be included in the project JHipster Control Center:
- discussion at https://groups.google.com/forum/#!topic/jhipster-dev/w-7tXPnIjlE
- project at https://github.com/jhipster/jhipster-control-center

It is currently developped by 2 interns at Ippon (@nassimerrahoui and @adilabed)

**Comment by maznag** [comment]
@pascalgrimaud thanks for this information.
