### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by maqeelqureshi** [jhipster/jhipster-dotnetcore#2]
This does not work
npm install -g generator-jhipster-jhipster-dotnetcore

also tried 
npm install -g https://github.com/jhipster/jhipster-dotnetcore.git

Error details
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: ERROR! The generator-jhipster-jhipster-dotnetcore blueprint provided is not installed. Please install it using command npm i -g generator-jhipster-jhipster-dotnetcore.
    at Environment.error (/usr/local/lib/node_modules/generator-jhipster/node_modules/yeoman-environment/lib/environment.js:176:40)
    at module.exports.error (/usr/local/lib/node_modules/generator-jhipster/generators/generator-base.js:1427:18)
    at shelljs.exec (/usr/local/lib/node_modules/generator-jhipster/generators/generator-base-private.js:790:22)
    at /usr/local/lib/node_modules/generator-jhipster/node_modules/shelljs/src/exec.js:127:9
    at ChildProcess.exithandler (child_process.js:282:5)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)

**Comment by danielpetisme** [comment]
Thanks for reporting the issue. 
Until an official release, can you use the method describe in 
https://www.jhipster.tech/modules/creating-a-blueprint/
Section **Running local Blueprint version for development**

**Comment by timmi4sa** [comment]
@danielpetisme Thanks a lot, was able to "npm link" inside this repository cloned to my local disk (on MacOS). Then I created a folder for my app and went in there (cd <appname>), did "npm link generator-jhipster-dotnetcore" which created a folder "node_modules" inside. After running "jhipster -d --blueprint dotnetcore" I see that the blueprint is picked up (as evidenced in launch sequence of jHipster: "INFO! Options: d: true, blueprint: dotnetcore, from-cli: true") but it generates Java application nevertheless. Is there some questionnaire answer that I choose that screws things up?

Note: I have "dotnet" available as part of 2.2.300 SDK installed on my MacOS.

**Comment by YogeshD-Hexaware** [comment]
404 error for   **npm install -g generator-jhipster-dotnetcore**

> npm ERR! code E404
> npm ERR! 404 Not Found: generator-jhipster-dotnetcore@latest
>

**Comment by YogeshD-Hexaware** [comment]
> @danielpetisme Thanks a lot, was able to "npm link" inside this repository cloned to my local disk (on MacOS). Then I created a folder for my app and went in there (cd ), did "npm link generator-jhipster-dotnetcore" which created a folder "node_modules" inside. After running "jhipster -d --blueprint dotnetcore" I see that the blueprint is picked up (as evidenced in launch sequence of jHipster: "INFO! Options: d: true, blueprint: dotnetcore, from-cli: true") but it generates Java application nevertheless. Is there some questionnaire answer that I choose that screws things up? (I chose monolithic with Postgres, no distributed cache, with Angular)
> 
> Note: I have "dotnet" available as part of 2.2.300 SDK installed on my MacOS.

same errors. it is still generating java files. 
Please update readMe with more details

**Comment by ivanmonteiro** [comment]
Tried installing with npm and yarn, both 404 not found.  Also tried local install of this blueprint, but when I run "jhipster -d --blueprint dotnetcore" it creates only java files.

Any solution to this?

**Comment by ivanmonteiro** [comment]
> > @danielpetisme Thanks a lot, was able to "npm link" inside this repository cloned to my local disk (on MacOS). Then I created a folder for my app and went in there (cd ), did "npm link generator-jhipster-dotnetcore" which created a folder "node_modules" inside. After running "jhipster -d --blueprint dotnetcore" I see that the blueprint is picked up (as evidenced in launch sequence of jHipster: "INFO! Options: d: true, blueprint: dotnetcore, from-cli: true") but it generates Java application nevertheless. Is there some questionnaire answer that I choose that screws things up? (I chose monolithic with Postgres, no distributed cache, with Angular)
> > Note: I have "dotnet" available as part of 2.2.300 SDK installed on my MacOS.
> 
> same errors. it is still generating java files.
> Please update readMe with more details

Having the same issues, jhipster generates only java files

**Comment by danielpetisme** [comment]
@YogeshD-Hexaware Thanks for raising the issue.
Since the blueprint is not yet published on npm official registry you can't use `npm install -g generator-jhipster-dotnetcore` right now. 
We're planning a first release, meanwhile use the repo url just as you mentionned.
We  are moving as fast as we  can to provide a first public version this summer I hope.
Feel free to contribute if you can/want.

**Comment by danielpetisme** [comment]
Fixed withe the presence in the npm registry
https://www.npmjs.com/package/generator-jhipster-dotnetcore
