### ISSUE TITLE
Problem with multiple many-to-many relationships in JDL

### ISSUE THREAD

**Issue by ivanmonteiro** [jhipster/jhipster-dotnetcore#228]
##### **Overview of the issue**

When defining multiple many-to-many relationships with jdl, the Join Entity class is created with the same contents of the first relationship, for all relationships. This causes complier error because the same class is created again and again.

##### **Reproduce the error**

Create a jdl with two or more many-to-many relationships and generate the files with jhipster

This creates three classes implementing IJoinedEntity for the many-to-many relationships, but with exactly the same source code for them.

  <details>
  <summary>JDL definitions</summary>
  <pre>
entity Product {
    name String
}

entity Category {
    name String
}

entity Kit {
    name String
}

relationship ManyToMany {
    Order{products(name)} to Product{orders}
    Category{products(name)} to Product{categories}
    Kit{products(name)} to Product{kits}
}

relationship ManyToOne {
    Kit{usuario(login)} to User
    Produto{usuario(login)} to User
}
  </pre>
  </details>

##### **Related issues**

Might be related to #224

##### **JHipster configuration**

Using master version of dotnet generator

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by nicolas63** [comment]
I have look this issue but i have no idea how to resolve it. If anybody can help @jhipster/developers
