### ISSUE TITLE
NullReferenceException related to sorting/paging

### ISSUE THREAD

**Issue by ivanmonteiro** [jhipster/jhipster-dotnetcore#229]
##### **Overview of the issue**

I get the following NullReferenceException when viewing any listing page:

Exception has occurred: CLR/System.NullReferenceException
Ocorreu uma exceção do tipo "System.NullReferenceException" em JHipsterNet.dll, mas ela não foi manipulada no código do usuário: 'Object reference not set to an instance of an object.'
   em JHipsterNet.Pagination.Binders.PageableBinder.ResolveSortArgument(QueryString queryString) em src\JHipsterNet\Pagination\Binders\PageableBinder.cs:linha 57
   em JHipsterNet.Pagination.Binders.PageableBinder.ResolvePageableArgumentFromQueryString(QueryString queryString) em src\JHipsterNet\Pagination\Binders\PageableBinder.cs:linha 34
   em JHipsterNet.Pagination.Binders.PageableBinder.BindModelAsync(ModelBindingContext bindingContext) em src\JHipsterNet\Pagination\Binders\PageableBinder.cs:linha 20
   em Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BinderTypeModelBinder.<BindModelAsync>d__2.MoveNext()

##### **Reproduce the error**

Using the latest master version, create some entities and go to the listing page of any of the created entities and the exception is thrown on the backend

##### **Related issues**

#176 

##### **Suggest a Fix**

On QueryStringExtensions.cs file change GetParameterValues method: 
To this:
```
        public static string[] GetParameterValues(this QueryString query, string name)
        {
            if (query == null || string.IsNullOrEmpty(name)) return new string[0];
            var parameters = QueryHelpers.ParseQuery(query.ToString());
            return parameters.ContainsKey(name) ? parameters[name].ToArray() :  new string[0];
        }
```

So the code that uses this method can safely run a foreach with the result without a null reference exeption.

##### **JHipster configuration**
Using master version of this repository

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by nicolas63** [comment]
Can you create a PR with the fix and ask @maznag to review ?

**Comment by ivanmonteiro** [comment]
Sure

**Comment by ivanmonteiro** [comment]
> Can you create a PR with the fix and ask @maznag to review ?

I will do that this weekend
