### ISSUE TITLE
Redirect loop using pagination and quickly switching from one entity's list page to another

### ISSUE THREAD

**Issue by ivanmonteiro** [jhipster/jhipster-dotnetcore#240]
##### **Overview of the issue**

When you open up another entity page while the current request is not finished, it seems that it causes a redirect loop.
This can possibly cause a Denial of Service.

It goes on like this:
Manually Open EntityA list page
Request for EntityA listing begins

Manually Open EntityB list page
Request for EntityB listing begins

Request for EntityA listing ends
Get redirected back to List A page - https://localhost:5001/EntityA?page=1&size=20&search=&sort=id,asc

Request for EntityB listing ends
Get redirected back to EntityB list page - https://localhost:5001/EntityB?page=1&size=20&search=&sort=id,asc

And this goes on as a redirect loop with a frequency of about 10 times/sec (not surpisingly as 100ms is about the mean loading time of a request on my machine). 

##### **Reproduce the error**

Create at least two entities with pagination enabled
Go to listing page of entityA (example: localhost/entityA).
WHILE it is still loading switch to another entity listing page (example: localhost/entityB).

If your response from the server is too fast to reproduce this, try creating some more "rows" of the entity.
Or add wait time on backend like 500ms-1000ms (eg `await Task.Delay(2000);`.

##### **Related issues**

Probably related to sorting/paging feature since I can only reproduce with paging enabled - See issues #176 #226 

##### **JHipster Version(s)**

Using current master version of this dotnet generator repository

##### **JHipster configuration**

  <details>
  <summary>JDL definitions</summary>
  <pre>
entity EntityA {
    name String
}

entity EntityB {
    name String
}

paginate EntityA, EntityB with pagination

  </pre>
  </details>

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by ivanmonteiro** [comment]
This seems to be related to the clientside request callback calling the router to change the url.
Since the previous request did not finish before we switched pages, when it completes, it calls the onSuccess function:
ClientApp/src/app/entites/entityname/entityname.component.ts
`
  protected onSuccess(data: ICliente[] | null, headers: HttpHeaders, page: number): void {
    this.totalItems = Number(headers.get('X-Total-Count'));
    this.page = page;
    this.ngbPaginationPage = this.page;
    this.router.navigate(['/cliente'], {
      queryParams: {
        page: this.page,
        size: this.itemsPerPage,
        search: this.currentSearch,
        sort: this.predicate + ',' + (this.ascending ? 'asc' : 'desc'),
      },
    });
    this.clientes = data || [];
  }
`

**Comment by ivanmonteiro** [comment]
I'm not sure how we can change this behaviour.
Maybe cancelling pending requests when the user changes the current page, is it possible?

**Comment by nicolas63** [comment]
Can you test this on java if they are the same issue ?

**Comment by ivanmonteiro** [comment]
> Can you test this on java if they are the same issue ?

@nicolas63 I just tested on java version 6.9.0, added a delay of 2 seconds on both EntityNamesResource.java file (so I have time to click the navbar and switch from one entity to another)
And it shows the same behaviour of the dotnet version.

**Comment by ivanmonteiro** [comment]
@nicolas63 so it seems to be related to the main jhipster generator

**Comment by maznag** [comment]
This isn't related to the sorting/paging feature added to the backend.

It's indeed an issue of the frontend (main generator JHipster) which was fixed for v6.9.1 (https://www.jhipster.tech/2020/06/01/jhipster-release-6.9.1.html). See https://github.com/jhipster/generator-jhipster/issues/11768 and https://github.com/jhipster/generator-jhipster/pull/11773 for more details.

**Comment by nicolas63** [comment]
Ok so can you create an issue in main generator and reference this issue on it ?

**Comment by ivanmonteiro** [comment]
> Ok so can you create an issue in main generator and reference this issue on it ?

Yes, I will create an issue on the main generator. This one remais open or close?

**Comment by nicolas63** [comment]
Nice thank you @maznag for this information. @ivanmonteiro can you try with 6.9.1 ?

**Comment by ivanmonteiro** [comment]
> Nice thank you @maznag for this information. @ivanmonteiro can you try with 6.9.1 ?

I will test with 6.9.1 today and get back to you

**Comment by ivanmonteiro** [comment]
@maznag I just locally upagraded  the dotnet generator to use tha main generator v6.9.1 and the issue is solved.
Thank you @maznag  and @maznag

**Comment by ivanmonteiro** [comment]
There is a dependabot PR on dependencies branch that upgrades the version of main generator to v6.9.1 #238 
Maybe merge it on branch?

**Comment by nicolas63** [comment]
Yes, i will do this today

**Comment by nicolas63** [comment]
merged #241. Thank you @ivanmonteiro for this bug report
