### ISSUE TITLE
Is there any C# API for Liquibase/Flyway to manage DB changes  instead of EF Data Migration ?

### ISSUE THREAD

**Issue by maznag** [jhipster/jhipster-dotnetcore#249]
Is there any C# API for Liquibase/Flyway to manage DB changes  instead of EF Data Migration ?

**Comment by nicolas63** [comment]
Why do you need this ? Liquibase already work and i think flyway too but you need to create changeset manually

**Comment by maznag** [comment]
Where do Liquibase already work? it isn't configured for the JHipster.net project ?

I need it to manage database changes like as for main generator-jhipster (with Liquibase). I'm talking about that https://www.liquibase.org (Only for Java). I think it doesn't exist for .Net.

I found this package https://www.nuget.org/packages/Liquibase.Cli/ but it isn't widely used and the project doesn't even exist on Github.

After a search on the net I also found these projects:

* https://github.com/lecaillon/Evolve
* https://github.com/fluentmigrator/fluentmigrator

My need is to manage database changes automatically as for Java Hipster.

**Comment by nicolas63** [comment]
Liquibase is not configured by jhipster.net but you can use it if you want (yes it's a java tool but you can use it). 
Why do you need other tool than EF Data Migration ? the principle is exactly the same than liquibase

Yes today the project don't generate migration but if they is already an issue on it (https://github.com/jhipster/jhipster-dotnetcore/issues/98)
and @ivanmonteiro has documented how to use migration manually here (https://github.com/jhipster/jhipster-dotnetcore#using-database-migrations)

**Comment by ivanmonteiro** [comment]
Personally I dont like liquibase. The main reason is because of its xml configuration files. I find them to be too verbose.

I'm more inclined to use migrations that you can write them using c# code and more in the philosophy line of ruby on rails migrations. 
The benefits of compiling your migration code and being able to read it easily are really compelling to me.

About the Dotnet EF Migrations, I think the migrations itself are ok but the .desin.cs files and the snapshopt.cs files I dont like them.

As an alternative, one of the projects that I have used in the past was the FlientMigrator, but it was before dotnet core was around. It is similar to the EF Migrations but somewhat cleaner and it seems to support dotnet core. Check it out: https://fluentmigrator.github.io/

**Comment by maznag** [comment]
@nicolas63 @ivanmonteiro thank you for your feedbacks.

I didn't pay attention that there is already an open issue for the data migration. So we can close this one :-)

Personally, I only used Liquibase for Java projects and I don't have a problem with it and I still use it.

This year I'm starting to be interested to dotnet core. I'm currently working on two different projects for a client: Angular/Spring Boot (Java)  and Angular/Dotnet Core.  In both I use JHipster of course.

So I wanted to know which better tool to use to track and manage database changes. I see that there is EF Data Migration tool but I never used it and I wonder if Liquibase implementation exists for Dotnet Core (answer NO).

I'm going to try EF since we can do code First and generate the migration after.

So, you think EF Data Migration is the best solution for the JHipster.Net project ?

**Comment by ivanmonteiro** [comment]
> @nicolas63 @ivanmonteiro thank you for your feedbacks.
> 
> I didn't pay attention that there is already an open issue (#98) for the data migration. So we can close this one :-)
> 
> Personally, I only used Liquibase for Java projects and I don't have a problem with it and I still use it.
> 
> This year I'm starting to be interested to dotnet core. I'm currently working on two different projects for a client: Angular/Spring Boot (Java) and Angular/Dotnet Core. In both I use JHipster of course.
> 
> So I wanted to know which better tool to use to track and manage database changes. I see that there is EF Data Migration tool but I never used it and I wonder if Liquibase implementation exists for Dotnet Core (answer NO).
> 
> I'm going to try EF since we can do code First and generate the migration after.
> 
> So, you think EF Data Migration is the best solution for the JHipster.Net project ?

I think ef migrations it is good enough, but not perfect. We still have to run the dotnet ef tool to generate them.

And I would be happy to see improvements on migration on jhipster.net, like  generation of migration code automatically when entities are changed, see issue #98. 
Or even choosing other migration library if it seems better to use.

Maybe we shoud discuss further there, and feel free to propose new solutions

**Comment by nicolas63** [comment]
For me, ef migration is just THE ONE solution for dotnet project. You can do exactly the same thinks than liquibase (apply changes and rollback)
I think the better to choose is to test it 😄 

`do code First and generate the migration after.` 
Yes, if you choose code first approach.

I'am very interesting to have feedback from your client project. 

For question like this or other discussion don't hesitate to use gitter (https://gitter.im/JHipster-NET/jhipster-dotnetcore)
