### ISSUE TITLE
Change webpack proxy port

### ISSUE THREAD

**Issue by EnmanuelReyes** [jhipster/jhipster-dotnetcore#257]
##### **Overview of the issue**

The .NET CORE application gets deployed using port 5001 but the webpack proxy points to localhost:8080, which is the default for the java application.

##### **Motivation for or Use Case**

So we can run the angular app individually with Browsersync.

##### **Reproduce the error**

Generate an application using this blueprint.

##### **Suggest a Fix**

I truly don't know if we should change the proxy port or the port of the .net application.

##### **JHipster Version(s)**

```
/Users/enmanuelreyes/Documents/Software/Fragmento/msc/bills-gateway
└── (empty)

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "nativeLanguage": "en"
    },
    "namespace": "Fragmento",
    "databaseType": "mssql",
    "authenticationType": "jwt",
    "prodDatabaseType": "mysql",
    "jhipsterVersion": "6.9.1",
    "applicationType": "monolith",
    "baseName": "mscbills",
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1592449142885,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [
      {
        "name": "generator-jhipster-dotnetcore",
        "version": "1.0.0"
      }
    ],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": ["en", "es"],
    "blueprints": [
      {
        "name": "generator-jhipster-dotnetcore",
        "version": "1.0.0"
      }
    ]
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.6+10, mixed mode)

git version 2.27.0

node: v10.15.3

npm: 6.4.1

yeoman: 3.1.1

yarn: 1.12.3

Docker version 19.03.1, build 74b1e89

docker-compose version 1.24.1, build 4667896b
##### **Browsers and Operating System**

MacOS Catalina 10.15.4

-   [✅] Checking this box is mandatory (this is just to show you read everything)

**Comment by ivanmonteiro** [comment]
I have noticed it too, took me some minutes to figure out where to change the port (webpack.dev.js). 
It certainly needs to be changed somewhere, but I'm also not sure if on the client configuration side or change the ports of the dotnet backend.

**Comment by nicolas63** [comment]
Yes, i have change port in the generator but it didn't work. I need more time for investigate.

**Comment by nicolas63** [comment]
The port is change, now all is ok. You can try it with run `dotnet run` ans `npm start`.
