### ISSUE TITLE
Create jhipster dotnet version variable 

### ISSUE THREAD

**Issue by nicolas63** [jhipster/jhipster-dotnetcore#267]
##### **Overview of the feature request**

Create jhipster dotnet version variable 

##### **Motivation for or Use Case**

Today i manually update jhispter dotnet version in generated readme

##### **Related issues or PR**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by nicolas63** [comment]
For the implementation we juste need to reproduce jhispterVersion behavior

**Comment by romain325** [comment]
Is there already a "References" file or do we need to create it?

**Comment by nicolas63** [comment]
In this file (https://github.com/jhipster/jhipster-dotnetcore/blob/master/generators/common/templates/dotnetcore/README.md.ejs) you can find <%= jhipsterVersion %> who is declare by the main generator, the idea is to create an jhipsterDotnetVersion from package version like here (https://github.com/jhipster/generator-jhipster/blob/d66bc7a27edad0bb670af3500856c8da11fb7702/generators/server/index.js) 

Or maybe we can use blueprint versvion who is declare here (https://github.com/jhipster/generator-jhipster/blob/5b7ca41e30b745794e08172fef1035c2d4e25b8d/generators/app/index.js) 

```
 this.blueprintVersion && (config.blueprintVersion = this.blueprintVersion);
```

you can try ```this.config.get('blueprintVersion');```

**Comment by romain325** [comment]
Alright thx !  it's done, i'll just make it in another branch (i havent checkout master before creating the new branch lol)
