### ISSUE TITLE
Add DTO generation 

### ISSUE THREAD

**Issue by nicolas63** [jhipster/jhipster-dotnetcore#274]
##### **Overview of the feature request**

Generate DTO and transform the entities to the DTO with AutoMapper

##### **Motivation for or Use Case**

Today we can only generate entities 

##### **Related issues or PR**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by ivanmonteiro** [comment]
I'm working on this on my branch and hope to provide a PR draft soon.

**Comment by ivanmonteiro** [comment]
Claimed bug bounty https://opencollective.com/generator-jhipster/expenses/22014
