### ISSUE TITLE
Add service layer 

### ISSUE THREAD

**Issue by nicolas63** [jhipster/jhipster-dotnetcore#275]
##### **Overview of the feature request**

Give the possibility to generate service layer 

##### **Motivation for or Use Case**

Today all code is in controller 

##### **Related issues or PR**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by ivanmonteiro** [comment]
Just to notice that I'm working on it, while adding dto generation I had to enable service at it is a pre-requisite.
I'll do a draft PR soon with service layer generation
