### ISSUE TITLE
Create repository layer 

### ISSUE THREAD

**Issue by nicolas63** [jhipster/jhipster-dotnetcore#276]
##### **Overview of the feature request**

Create a repository layer with unitofwork pattern

##### **Motivation for or Use Case**

Today we use directly the datacontext in the controller 

##### **Related issues or PR**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by romain325** [comment]
Just to notice that I'm actually working on it 
I'll do a draft when I have something that is working

**Comment by ivanmonteiro** [comment]
I'm interested on working on this issue (if possible)

**Comment by nicolas63** [comment]
Yes you can ! I have an example of what I want i send you this as soon as possible.

**Comment by nicolas63** [comment]
Exemple with unitofwork and generic repo to adapt with our pagination 

[ServicesMobiles.zip](https://github.com/jhipster/jhipster-dotnetcore/files/5308086/ServicesMobiles.zip)

**Comment by ivanmonteiro** [comment]
> Exemple with unitofwork and generic repo to adapt with our pagination
> 
> [ServicesMobiles.zip](https://github.com/jhipster/jhipster-dotnetcore/files/5308086/ServicesMobiles.zip)

Thanks for the example you sent.
One quesion, would the generic repository be sufficient for all entities or one repository per entitiy would be also needed to be generated?

**Comment by nicolas63** [comment]
You need per entity an interface who implement IGenericRepo 

'public interface ISampleRepository : IGenericRepository<Sample> { } '

And the repo who implement this interface and inherite of GenericRepo

'public class SampleRepository : GenericRepository<Game>, ISampleRepository { public SampleRepository(IUnitOfWork context) : base(context) { } } '

**Comment by maznag** [comment]
@nicolas63 @ivanmonteiro I think we don't need to implement UnitofWork. GenericRepository and one repository per entity is sufficient. Repository will be used per Service layer

I recently implemented the Repository Layer for one of my projects. here is an example without search functionality.

What do you think ?

- IGenericRepository
```
namespace SampleApp.Data.Interfaces
{
    public interface IGenericRepository<TEntity> where TEntity : class
    {
        Task<TEntity> FindAsync(object id);

        Task<IEnumerable<TEntity>> FindAllAsync();

        Task<IPage<TEntity>> FindAllAsync(IPageable pageable);

        Task<int> CountAsync();

        Task<TEntity> CreateAsync(TEntity entity);

        Task<bool> CreateRangeAsync(params TEntity[] entities);

        Task<TEntity> UpdateAsync(TEntity entity);

        Task<bool> UpdateRangeAsync(params TEntity[] entities);

        Task DeleteAsync(Guid id);

        Task DeleteAsync(TEntity entity);

        Task<int> SaveChangesAsync(CancellationToken cancellationToken = default);

        void Dispose();
    }
}
```
- GenericRepository

```
namespace SampleApp.Data.Repositories
{

    public class GenericRepository<TEntity> : IDisposable, IGenericRepository<TEntity> where TEntity : class
    {
        protected ApplicationDatabaseContext _context;
        protected readonly DbSet<TEntity> _dbSet;

        public GenericRepository(ApplicationDatabaseContext context)
        {
            _context = context;
            _dbSet = context.Set<TEntity>();
        }

        public virtual async Task<TEntity> FindAsync(object id)
        {
            return await _dbSet.FindAsync(id);
        }

        public async Task<IEnumerable<TEntity>> FindAllAsync()
        {
            using var findTask = Task.FromResult(_dbSet.AsEnumerable());
            return await findTask;
        }

        public async Task<IPage<TEntity>> FindAllAsync(IPageable pageable)
        {
            using var pagingTask = Task.FromResult(_dbSet.AsQueryable().UsePageable(pageable));
            return await pagingTask;
        }

        public virtual async Task<int> CountAsync()
        {
            using var countTask = _dbSet.CountAsync();
            return await countTask;
        }

        public virtual async Task<TEntity> CreateAsync(TEntity entity)
        {
            await _dbSet.AddAsync(entity);
            await _context.SaveChangesAsync();
            return entity;
        }

        public virtual async Task<bool> CreateRangeAsync(params TEntity[] entities)
        {
            await _dbSet.AddRangeAsync(entities);
            await SaveChangesAsync();
            return true;
        }

        public virtual async Task<TEntity> UpdateAsync(TEntity entity)
        {
            _dbSet.Update(entity);
            await _context.SaveChangesAsync();
            return entity;
        }

        public virtual async Task<bool> UpdateRangeAsync(params TEntity[] entities)
        {
            _dbSet.UpdateRange(entities);
            await SaveChangesAsync();
            return true;
        }

        public virtual async Task DeleteAsync(Guid id)
        {
            var entity = await FindAsync(id);
            await DeleteAsync(entity);
        }

        public virtual async Task DeleteAsync(TEntity entity)
        {
            using var removeTask = Task.FromResult(_dbSet.Remove(entity));
            await removeTask;
            await _context.SaveChangesAsync();
        }

        public virtual async Task<int> SaveChangesAsync(CancellationToken cancellationToken = default)
        {
            using var saveChangeTask = _context.SaveChangesAsync(cancellationToken);
            return await saveChangeTask;
        }

        public void Dispose()
        {
            _context?.Dispose();
        }
    }
}
```
- ISampleRepository
```
namespace SampleApp.Data.Interfaces
{
    public interface ISampleRepository: ISampleRepository<SampleEntity>
    {
        Task<SampleEntity> CreateOrUpdateAsync(sampleEntity);
    }
}
```

- Sample repository

```
namespace SampleApp.Data.Repositories
{
    public class SampleRepository : GenericRepository<SampleEntity>, ISampleRepository
    {
        public SampleRepository(ApplicationDatabaseContext context) : base(context)
        {
        }

        public async Task<SampleEntity> CreateOrUpdateAsync(SampleEntity sampleEntity)
        {
            bool isExists = _dbSet.Exists(e=> e.Id == SampleEntity.Id);
            if(SampleEntity.Id != Guid.Empty && isExists)
            {
                _dbSet.Update(sampleEntity);
               // force the navigation property to be in modified state
                _context.Entry(sampleEntity).Reference(e0=> e0.SampleEntity2).IsModified = true;
                using Task<int> saveTask = _context.SaveChangesAsync();
                await saveTask;
            } else
            {
                using Task<SampleEntity> createTask = base.CreateAsync(sampleEntity);
                await createTask;
            }
            return sampleEntity;
        }

        // Add more specific methods here

    }
}
```

**Comment by nicolas63** [comment]
@maznag you can take a look on the zip in before post.

My implementation is close to yours my unit of work is just an interface on dbcontext

**Comment by maznag** [comment]
Ok. So I can delete my post which is useless since your zip contains everything ?

**Comment by ivanmonteiro** [comment]
> @nicolas63 @ivanmonteiro I think we don't need to implement UnitofWork. GenericRepository and one repository per entity is sufficient. Repository will be used per Service layer
> 
> I recently implemented the Repository Layer for one of my projects. here is an example without search functionality.
> 
> What do you think ?

@maznag Both implementations are very similar indeed but yours is simpler. I tend to prefer simplicity. 

Is the unit of work class necessary in your opinion @nicolas63?

**Comment by nicolas63** [comment]
Yes i think, when we want mock the dbcontext context it's easier. For the simplicity it's just an interface on the dbcontext so it's not too complex

**Comment by ivanmonteiro** [comment]
> Yes i think, when we want mock the dbcontext context it's easier. For the simplicity it's just an interface on the dbcontext so it's not too complex

@nicolas63 I had not considered that, you have a good point about testing (although I have not needed to mock dbcontext). 

I'll proceed with your approach @nicolas63

**Comment by ivanmonteiro** [comment]
@maznag thank you for your code and the time you took to express your opinions here, they are valuable and your code surely will help me as a reference
