### ISSUE TITLE
Bad indentation on enum generation

### ISSUE THREAD

**Issue by nicolas63** [jhipster/jhipster-dotnetcore#287]
##### **Overview of the issue**

The enum  generation apply bad indentation : 

`
    public enum Language {
        FRENCH,        ENGLISH,        SPANISH,    }

`

##### **Motivation for or Use Case**

the good indentation is : 

`
    public enum Language {
        FRENCH,       
        ENGLISH,        
        SPANISH   
   }

`

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by nicolas63** [comment]
@ivanmonteiro Can you take a look please ?

**Comment by ivanmonteiro** [comment]
> @ivanmonteiro Can you take a look please ?

Yes, I'll take a look at it soon
