### ISSUE TITLE
Refactoring question about ProblemDetailsException

### ISSUE THREAD

**Issue by ivanmonteiro** [jhipster/jhipster-dotnetcore#296]
This question is about the ProblemDetailsException on this folder:

![image](https://user-images.githubusercontent.com/891084/87075579-f2551800-c1f6-11ea-844e-32a303d51a05.png)

Those ProblemDetailsException are used by the UserService and the api/main project.

I was tempted to move them to the Crosscutting project but it depends on a package that is not available for .net standard (crosscut layer is .net standard library to help sharing code with other clients, like blazor). 
The package is Hellang.Middleware.ProblemDetails.
So it was not possible for me to move those ProblemDetailsExceptions to the crosscutting layer.

I ended up creating a Infrastructure layer and putting them there along with other infrastructure code. 
Then and adding the Hellang.Middleware.ProblemDetails package to the infrastructure project, and making the Infrastructure project a .net CORE library project. 

I want to know: 

- Is this going to be an issue (infrastructure layer .net core project instead of .net standard)? 

I so, then we should figure out a way to get around the ProblemDetails package not being compatible with .net STANDARD. 
A guess is inheriting from Exceptions instead of ProblemDetailsException.

**Comment by ivanmonteiro** [comment]
Also, should this whole web folder be moved?

**Comment by nicolas63** [comment]
I think is a conception error. The services need to be independent of this exception. Hellang do not support .netstandard bécasse it's a .net core middleware so only controllers must have the logic of this exception. 
I prefer this approach 
`public void ConfigureServices(IServiceCollection services)
{
    services
        .AddProblemDetails(setup =>
        {
            setup.IncludeExceptionDetails = _ => !Environment.IsDevelopment();
            setup.Map<OutOfCreditException>(exception => new OutOfCreditProblemDetails
            {
                Title = exception.Message,
                Detail = exception.Description,
                Balance = exception.Balance,
                Status = StatusCodes.Status403Forbidden,
                Type = exception.Type
            });
        })

    ...

}`

Is like mapping 

You can found more detail here ( https://lurumad.github.io/problem-details-an-standard-way-for-specifying-errors-in-http-api-responses-asp.net-core)

Maybe we can create extension method who map all custom exception to problem detail exception .

What do you think?

**Comment by ivanmonteiro** [comment]
Would new exception classes need to be created and used on services (putting them on projectname.crosscutting.exceptions)?

So whe can map them to problem details on the application?

**Comment by nicolas63** [comment]
You can use existing exceptions but remove inherite of problem detail and just do mapping in the startup with an extension method

**Comment by ivanmonteiro** [comment]
> You can use existing exceptions but remove inherite of problem detail and just do mapping in the startup with an extension method

Sounds good, I will give it a try
