### ISSUE TITLE
webpack rtl.scss Error 

### ISSUE THREAD

**Issue by manisi** [jhipster/jhipster-dotnetcore#298]
ERROR in ./src/content/scss/vendor.scss (./node_modules/css-loader/dist/cjs.js!./node_modules/postcss-loader/src!./node_modules/sass-loader/dist/cjs.js??ref--11-3!./src/content/scss/vendor.scss)
         Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
         SassError: Can't find stylesheet to import.
            ╷
         12 │ @import 'src/Dotnetcoresample/ClientApp/src/content/scss/rtl.scss';
            │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            ╵
           /Users/developer/Desktop/dotnetcoresample/src/Dotnetcoresample/ClientApp/src/content/scss/vendor.scss 12:9  root stylesheet
         npm ERR! code ELIFECYCLE
         npm ERR! errno 2
         npm ERR! dotnetcoresample@0.0.1-SNAPSHOT webpack: `node --max_old_space_size=4096 node_modules/webpack/bin/webpack.js "--config" "webpack/webpack.dev.js" "--env.stats=minimal"`
         npm ERR! Exit status 2
         npm ERR! 

##### **JHipster Version(s)**

```
/Users/developer
└── generator-jhipster@6.10.1 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "nativeLanguage": "en"
    },
    "namespace": "DanaIns",
    "databaseType": "sqllite",
    "authenticationType": "jwt",
    "prodDatabaseType": "mysql",
    "jhipsterVersion": "6.9.1",
    "applicationType": "monolith",
    "baseName": "dotnetcoresample",
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1594448870275,
    "testFrameworks": ["gatling"],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [
      {
        "name": "generator-jhipster-dotnetcore",
        "version": "1.0.0"
      }
    ],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": ["en", "fa"],
    "blueprints": [
      {
        "name": "generator-jhipster-dotnetcore",
        "version": "1.0.0"
      }
    ]
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "1.8.0_242"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_242-b08)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.242-b08, mixed mode)

git version 2.20.1

node: v13.7.0

npm: 6.14.4

yeoman: 3.1.1

yarn: 1.21.1

Docker version 19.03.8, build afacb8b

docker-compose version 1.25.4, build 8d51620a

**Comment by nicolas63** [comment]
@manisi can you try #300 and confirm that this solves your problem ?

**Comment by manisi** [comment]
Hi ,
Thanks
reinstall generatore with : npm install -g generator-jhipster-dotnetcore
and then jhipster --blueprints dotnetcore
(Is the update generatore correct this way?)
The error still exists.
Thanks.


‫‪nicolas63‬‏ <‪notifications@github.com‬‏> در تاریخ سه‌شنبه ۱۴ ژوئیهٔ ۲۰۲۰
ساعت ۲۱:۲۵ نوشت:‬

**Comment by nicolas63** [comment]
no, it's not merged, you need to clone my fork (https://github.com/nicolas63/jhipster-dotnetcore) the fix is on master branch. 
After that, you can launch `npm link` in the folder (it's replacing your current version with mine) and test it.

**Comment by manisi** [comment]
Thanks alot.
thats ok. :)
way not exist language menu in navbar or select language in account setting?


‫‪nicolas63‬‏ <‪notifications@github.com‬‏> در تاریخ چهارشنبه ۱۵ ژوئیهٔ
۲۰۲۰ ساعت ۱۰:۴۰ نوشت:‬

**Comment by nicolas63** [comment]
yes, that's not normal. It's another bug

**Comment by nicolas63** [comment]
Can you retry with lastest version of my fork ?

**Comment by manisi** [comment]
that,s Ok
Thanks.

**Comment by nicolas63** [comment]
thank to you for your feedbacks ! 😃
