### ISSUE TITLE
not generate the required code for AutoMapperProfile class

### ISSUE THREAD

**Issue by manisi** [jhipster/jhipster-dotnetcore#309]
Hello
Does not generate the required code to use AutoMapper in AutoMapperProfile class file after new Entity generate.

##### **JHipster Version(s)**

```
/Users/developer
└── generator-jhipster@6.10.1 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "nativeLanguage": "en"
    },
    "namespace": "MyCompany",
    "databaseType": "mssql",
    "authenticationType": "jwt",
    "prodDatabaseType": "mysql",
    "jhipsterVersion": "6.10.0",
    "applicationType": "monolith",
    "baseName": "dotnetcoresample",
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1595143725750,
    "testFrameworks": ["gatling"],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [
      {
        "name": "generator-jhipster-dotnetcore",
        "version": "1.0.0"
      }
    ],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": ["en", "fa"],
    "blueprints": [
      {
        "name": "generator-jhipster-dotnetcore",
        "version": "1.0.0"
      }
    ]
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Newentity {
  name String,
  date LocalDate required,
  isdone Boolean
}
dto Newentity with mapstruct
service Newentity with serviceImpl

</pre>
</details>

##### **Environment and Tools**

openjdk version "1.8.0_242"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_242-b08)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.242-b08, mixed mode)

git version 2.20.1

node: v13.7.0

npm: 6.14.4

yeoman: 3.1.1

yarn: 1.21.1

Docker version 19.03.8, build afacb8b

**Comment by nicolas63** [comment]
@ivanmonteiro do you have any idea where this bug could come from ?

**Comment by ivanmonteiro** [comment]
> @ivanmonteiro do you have any idea where this bug could come from ?

With the command jhipster --with-entities --force the mapping is generated correctly, but using the entity generator (jhipster entity newEntity) the mapping is not generated.

I need to further investigate this.

**Comment by ivanmonteiro** [comment]
This code does not generate the mapping for new entity when using the entity generator (AutomapperProfile.cs.ejs):

```
           <%_ entities.forEach(entity => {
                    if(entity.definition.dto === 'mapstruct') { _%>
            CreateMap<<%= entity.name %>, <%= asDto(entity.name) %>>().ReverseMap();
            <%_
                    }
                });
            %>
```

**Comment by nicolas63** [comment]
Error: Copying template dotnetcore/src/Project/Service/Mapper/AutoMapperProfile.cs.ejs failed. [ReferenceError: /Users/developer/Desktop/dotnetcoresample/jhipster-dotnetcore/generators/entity-server/templates/dotnetcore/src/Project/Service/Mapper/AutoMapperProfile.cs.ejs:49
47| else {
48| if(dto === 'mapstruct') { _%>

        49| CreateMap<<%= entity.name %>, <%= asDto(entity.name) %>>().ReverseMap();
        50| <%
        51| }} %>
        52| %>

entity is not defined]
at module.exports.error (/Users/developer/Desktop/dotnetcoresample/jhipster-dotnetcore/node_modules/generator-jhipster/generators/generator-base.js:1590:15)
