### ISSUE TITLE
 serilog : console log and File log not the same content

### ISSUE THREAD

**Issue by manisi** [jhipster/jhipster-dotnetcore#310]
Hi,
config serilog in appsetings file for use console or file ,It is not the same log in consloe and File.

##### **JHipster Version(s)**

```
/Users/developer
└── generator-jhipster@6.10.1 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "nativeLanguage": "en"
    },
    "namespace": "MyCompany",
    "databaseType": "sqllite",
    "authenticationType": "jwt",
    "prodDatabaseType": "mysql",
    "jhipsterVersion": "6.10.0",
    "applicationType": "monolith",
    "baseName": "dotnetcoresample",
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1594795289451,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [
      {
        "name": "generator-jhipster-dotnetcore",
        "version": "1.0.0"
      }
    ],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": ["en", "fa"],
    "blueprints": [
      {
        "name": "generator-jhipster-dotnetcore",
        "version": "1.0.0"
      }
    ]
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "1.8.0_242"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_242-b08)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.242-b08, mixed mode)

git version 2.20.1

node: v13.7.0

npm: 6.14.4

yeoman: 3.1.1

yarn: 1.21.1

Docker version 19.03.8, build afacb8b

docker-compose version 1.25.4, build 8d51620a

**Comment by nicolas63** [comment]
@manisi if you have time can you help us to investigate this problem ?

**Comment by manisi** [comment]
> if you have time can you help us to investigate this problem ?

Yes, Sure 👍
