### ISSUE TITLE
Serve swagger on /admin/api-docs

### ISSUE THREAD

**Issue by nicolas63** [jhipster/jhipster-dotnetcore#311]
##### **Overview of the feature request**

Today swagger is only serve on /swagger 

##### **Related issues or PR**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by EnmanuelReyes** [comment]
HI, @nicolas63 I would like to help with this ticket.

What's really needs to be done / How do you expect to access the API docs?

**Comment by nicolas63** [comment]
Today our swagger is serve on /swagger 

On main generator the swagger-ui/index.html call an url swagger-resource
(https://github.com/jhipster/generator-jhipster/blob/master/generators/client/templates/angular/src/main/webapp/swagger-ui/index.html.ejs)

We need to analyse what is return by java version in this url to do the same thing

**Comment by EnmanuelReyes** [comment]
Hi @nicolas63 , I found a way to make it working, assign this issue to me if you can.
