### ISSUE TITLE
Fix file naming and move VM and DTO

### ISSUE THREAD

**Issue by nicolas63** [jhipster/jhipster-dotnetcore#313]
##### **Overview of the issue**

The Vm classes are renamed but not the file like 'LoginDTO' /'LoginVM'  
The file are in Project rather than Project.DTO 

'KeyAndPasswordDTO' ,etc need to be move to Project.DTO 

![image](https://user-images.githubusercontent.com/14818936/88711088-eaaed200-d117-11ea-840e-388dc8d1aad1.png)
![image](https://user-images.githubusercontent.com/14818936/88711108-f3070d00-d117-11ea-9500-8fb1dedb3a59.png)

##### **Motivation for or Use Case**

Fix file naming

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by nicolas63** [comment]
@ivanmonteiro can you treat this please ?

**Comment by ivanmonteiro** [comment]
> @ivanmonteiro can you treat this please ?

Sure,
I remember implementing this (maybe on the dto PR I'm not sure).

I will make sure to fix vm/dto naming soon.

**Comment by ivanmonteiro** [comment]
@nicolas63 should the project suffix be uppercase too? 
Currently it is ProjectName.Dto. Should it be renamed to upercase (to ProjectName.DTO)?

**Comment by nicolas63** [comment]
no it would be rather the opposite the entities to be named Dto because sonar detects smells codes (https://sonarcloud.io/project/issues?id=jhipster_jhipster-sample-app-dotnetcore&open=AXMvJE7ApL9noPyTDWYI&resolved=false&types=CODE_SMELL). 
But it's not very important. 

Thanks for your PR

**Comment by ivanmonteiro** [comment]
> no it would be rather the opposite the entities to be named Dto because sonar detects smells codes (https://sonarcloud.io/project/issues?id=jhipster_jhipster-sample-app-dotnetcore&open=AXMvJE7ApL9noPyTDWYI&resolved=false&types=CODE_SMELL).
> But it's not very important.
> 
> Thanks for your PR

I can rename to Dto its not problem for me.

**Comment by nicolas63** [comment]
@ivanmonteiro As you want, if your time permits, why not.
