### ISSUE TITLE
Display log messages on production and docker

### ISSUE THREAD

**Issue by ivanmonteiro** [jhipster/jhipster-dotnetcore#314]
##### **Overview of the issue**

When using the production profile, the console log only displays the application banner.

Specially when using docker, since it uses the console log, I see no log info about the application using `docker logs` command.

Maybe should log some information (specially request and db query time)

##### **Related issues**

Maybe related to #310 

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by nicolas63** [comment]
All our logs are in debug and production log level is Info

**Comment by ivanmonteiro** [comment]
> All our logs are in debug and production log level is Info

In debug mode it is a LOT of information, maybe in production be more selective of what to log.
For me its important in production to log the current request controller or action and if possible how long it took to complete and how long database queries takes to run.

**Comment by nicolas63** [comment]
close by #502
