### ISSUE TITLE
Add .editorconfig file to be included while generating the codebase

### ISSUE THREAD

**Issue by vraravam** [jhipster/jhipster-dotnetcore#332]
##### **Overview of the feature request**

For the past few years, I have used a '.editorconfig' file that I incorporate into each codebase. 

##### **Motivation for or Use Case**

This is very useful since most IDEs and text editors adhere to the configurations specified here - and thus, irrespective of which editor each team member uses, the formatting of the files are consistent.

An example of this (for dotnet-core with some of the common formatting rules) can be found [here](https://raw.githubusercontent.com/jhipster/jhipster-net/master/.editorconfig)

##### **Related issues or PR**

No

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by vraravam** [comment]
Closing this - since the PR was merged

**Comment by nicolas63** [comment]
This issue is not resolve the editorconfig was added on jhipster-net but not on the generator. For now the generated editorconfig is like (https://github.com/jhipster/jhipster-sample-app-dotnetcore/blob/master/.editorconfig)

**Comment by nicolas63** [comment]
We can apply coding style from dotnet runtime 
https://github.com/dotnet/runtime/blob/master/docs/coding-guidelines/coding-style.md
https://github.com/dotnet/runtime/blob/master/.editorconfig

**Comment by nicolas63** [comment]
this issue can be done in three step or three PR 
- [ ] Add .editorconfig with documentation for dotnet format (https://github.com/dotnet/format)
- [ ] Apply format on our solution 
- [ ] check format in ci for detect format error on pull request

**Comment by vraravam** [comment]
working on it

**Comment by vraravam** [comment]
>     * [ ]  Add .editorconfig with documentation for dotnet format (https://github.com/dotnet/format)

This is now done as part of this [PR](https://github.com/jhipster/jhipster-dotnetcore/pull/400)

**Comment by vraravam** [comment]
>     * [ ]  Apply format on our solution

this is now doen as part of [this PR](https://github.com/jhipster/jhipster-dotnetcore/pull/401)

**Comment by nicolas63** [comment]
I spent some time trying to fix the problems but the formatting organizes using directives in alphabetical order, so it depends on the name of the application. Maybe doing the formatting after the generation wasn't a bad idea. @ivanmonteiro what do you think?

**Comment by ivanmonteiro** [comment]
Does the generator correctly detect which files needs to be overwritten and the diff tool works correctly?

> I spent some time trying to fix the problems but the formatting organizes using directives in alphabetical order, so it depends on the name of the application. Maybe doing the formatting after the generation wasn't a bad idea. @ivanmonteiro what do you think?

As for the question you asked, would a "using directives ordering function" on the generator help? Or maybe disabling using directives sorting with:
```
dotnet_separate_import_directive_groups = false
dotnet_sort_system_directives_first = false
``` 
I have not tested this, though. Hope this can be of any help.

**Comment by nicolas63** [comment]
> dotnet_separate_import_directive_groups = false
> dotnet_sort_system_directives_first = false

I have already tested this but by looking at the source code i have see that it was necessary to delete this lines to disable alphabetical sort
