### ISSUE TITLE
Could not import a custom JDL, but console response has successful

### ISSUE THREAD

**Issue by robrui** [jhipster/jhipster-dotnetcore#34]
Hi again! I'm import a custom JDL (generated in JDL Studio, of course), and the console returns a success log.
```
PS C:\Users\rruiz\Desktop\test> jhipster import-jdl .\jhipster-jdl.jh --skip-checks
INFO! Using JHipster version installed globally
INFO! Executing import-jdl .\jhipster-jdl.jh
INFO! Options: skipChecks: true, from-cli: true, skip-checks: true
INFO! Found .yo-rc.json on path. This is an existing app
INFO! The JDL is being parsed.
INFO! No change in entity configurations, no entities were updated.
INFO! The JDL has been successfully parsed
```
But, in the dotnet solution, i didn't watch the models.
![imagen](https://user-images.githubusercontent.com/7157813/63612755-61ad2380-c5b5-11e9-8710-16b61f09f9d5.png)

NOTE: Without "skip checks", the message logs are similar.

Exists a solution (at least, temporally) for this incident?

Thanks a lot!

**Comment by danielpetisme** [comment]
Hi Roberto,
Thank you for exploring the blueprint. We are looking for .Net devs feedbacks and I really appreciate the time you are investing.


Unfortunately, the JDL features are not covered yet but it's clearly must have. Feel free to propose something, I can provide some guidance.

Again thank you.

**Comment by ivanmonteiro** [comment]
> Hi Roberto,
> Thank you for exploring the blueprint. We are looking for .Net devs feedbacks and I really appreciate the time you are investing.
> 
> Unfortunately, the JDL features are not covered yet but it's clearly must have. Feel free to propose something, I can provide some guidance.
> 
> Again thank you.

What is covered at the time?
