### ISSUE TITLE
I encounter an issue when deploying the Angular application to a server: ERROR Error: input must not be of zero length regarding the pagination.

### ISSUE THREAD

**Issue by NtsikaMngoma** [jhipster/jhipster-dotnetcore#344]
I am just making a simple get request to fetch all.

##### **Browsers and Operating System**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by NtsikaMngoma** [comment]
> > It's not in the project.
> 
> it's hidden file.
> 
> Do you have dotnet install on your machine with nginx ? you need to serve the application with `dotnet yourproject.dll`
> This command run the back-end but also serve the front-end
> if you want serve the app with nginx you can follow this (https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-3.1)

I have an understanding in deploying, but it seems as if this is where the underlying issue is: Showing NaN - 0 of 0 items on the actual page and ERROR TypeError: Cannot read property 'page' of undefined on console.

**Comment by nicolas63** [comment]
Can you give me your nginx conf for try it ?

**Comment by nicolas63** [comment]
@NtsikaMngoma any update ? How i can help you on this issue ?

**Comment by NtsikaMngoma** [comment]
I sorted this issue out. I just need assistance with search and filtering without having to use elasticsearch.
I see you dotnet application doesn't have that yet.

**Comment by nicolas63** [comment]
@NtsikaMngoma Can you describe the resolution here ? Maybe it will be useful for other people 
For search and filtering can you open an issue with the full description of what you want ?

**Comment by NtsikaMngoma** [comment]
I had mistakenly left out the page size for the pagination in the Angular component file and therefore, it was giving problems, but I was able to resolve it through debugging, as the error was reading:  ERROR TypeError: Cannot read property 'page' of undefined on console
