### ISSUE TITLE
Change dto json/dto structure

### ISSUE THREAD

**Issue by ivanmonteiro** [jhipster/jhipster-dotnetcore#355]
##### **Overview of the feature request**

Change dto to use the following structure:
`{ "id": 1, "regionName": "fg", "relationShipId": 1 }`

Currently dto uses this structure (the same structure of using entities):
`{ "id": 1, "regionName": "fg", "relationShip": { "id": "user-2", "relationShipName": "name", } }`

Some work will need to be done on .net side for the dto  code and entity framework code.

##### **Motivation for or Use Case**

For my use case it is is intersting to have a shorter/leaner json structure when using dto.

##### **Related issues or PR**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by nicolas63** [comment]
I will work on it
