### ISSUE TITLE
Serilog Issue on IIS

### ISSUE THREAD

**Issue by NtsikaMngoma** [jhipster/jhipster-dotnetcore#358]
I am encountering 500.36 ANCM Out-Of-Process Handler Load Failure, please assist with a guide on how to deploy to IIS Server as I think the issue is based around Serilog, because when I remove logging, the application runs.

**Comment by nicolas63** [comment]
How do you have configure IIS ? I have try this and it work fine. 
Step to reproduce : create a no managed app pool
![image](https://user-images.githubusercontent.com/14818936/92010998-bfd52080-ed4a-11ea-953e-21234e7eb680.png)

Create new WebSite on this app pool 

Publish your app : `dotnet publish --verbosity normal -c Release -o ./app/out ./YourApp.csproj`

Copy the content of ./app/out folder into IIS

**Comment by NtsikaMngoma** [comment]
Please send me a translated screenshot if possible. If this is what I need to do, I am going to test.

**Comment by nicolas63** [comment]
I cannot translate but the important part is CLR version with No Managed code

**Comment by NtsikaMngoma** [comment]
Okay, thanks. I will try and get back if it doesn't work.

**Comment by nicolas63** [comment]
@NtsikaMngoma if it's ok for you can you close this issue ?

**Comment by NtsikaMngoma** [comment]
I am still getting :  HTTP Error 500.30 - ANCM In-Process Start Failure  although I have added NoManagedAppPool

**Comment by nicolas63** [comment]
> 
> 
> I am still getting : HTTP Error 500.30 - ANCM In-Process Start Failure although I have added NoManagedAppPool

You have close this issue it's ok ?

**Comment by NtsikaMngoma** [comment]
Yep. It works!

**Comment by NtsikaMngoma** [comment]
Please review my other issues/requests.
