### ISSUE TITLE
Possibility to choose Dapper as ORM 

### ISSUE THREAD

**Issue by NtsikaMngoma** [jhipster/jhipster-dotnetcore#361]
Is it possible to write a repo the same as the entity framework, but using dapper instead of EF.

**Comment by nicolas63** [comment]
@NtsikaMngoma It's possible but I don't have the time to process this request and EF works well in most cases. If you still want this feature i can help you to do it on the generator

**Comment by NtsikaMngoma** [comment]
Sure, please assist.

**Comment by ivanmonteiro** [comment]
I would start by taking a look at the template files: `EntityController.cs.ejs ` and `Service.cs.ejs`.
If you want you can fork, change to your needs and use your custom generator:
https://github.com/jhipster/jhipster-dotnetcore#running-local-blueprint-version-for-development

**Comment by nicolas63** [comment]
Exactly, you can look EntityController.ejs and Service.ejs. 
For starting you can create a sample with dapper rather than ef maybe you can transform https://github.com/jhipster/jhipster-sample-app-dotnetcore.

When you have a sample who work with dapper you can copy your code in ejs files.

**Comment by maznag** [comment]
In my opinion, it is useless to **make the generator complex by adding more options** and EF core is works well and is sufficient in most cases . In addition, with Dapper, we should  hard-code SQL queries which facilitates the injection of the SQL code. Dapper can only be used for performance reasons for BigData applications. **I don't recommend adding this functionality to the this blueprint**. Developers can easily integrate Dapper with an application generated by **JHipter.NET**.

@nicolas63 @ivanmonteiro , if you agree we can close this issue !

**Comment by nicolas63** [comment]
Totally agree with you ! we can close this
