### ISSUE TITLE
No soft delete in Asp_Users Table

### ISSUE THREAD

**Issue by NtsikaMngoma** [jhipster/jhipster-dotnetcore#362]
Is there a way to implement soft deletes in the users able that you have reference to, as the current build deletes.

**Comment by nicolas63** [comment]
As a deactivating function ?

**Comment by NtsikaMngoma** [comment]
> As a deactivating function ?

Correct

**Comment by nicolas63** [comment]
This feature is already implemented. Maybe a bug ? 

On user management view you can click on Activated button 
![image](https://user-images.githubusercontent.com/14818936/92583694-ff43c580-f292-11ea-97f8-e59d6803b4c5.png)

**Comment by NtsikaMngoma** [comment]
> This feature is already implemented. Maybe a bug ?
> 
> On user management view you can click on Activated button
> ![image](https://user-images.githubusercontent.com/14818936/92583694-ff43c580-f292-11ea-97f8-e59d6803b4c5.png)

Okay, no. Is Actived/Deactivated not for account confirmation purposes? I am actually referring to the delete button.

**Comment by nicolas63** [comment]
Yes it is use the account confirmation but it you disable manually the user can't log in .

**Comment by NtsikaMngoma** [comment]
> Yes it is use the account confirmation but it you disable manually the user can't log in .

Okay, makes sense but I am talking about the delete button, on delete I would like to be able to retrieve the details for historic purposes/archive the user.

**Comment by nicolas63** [comment]
yes, but if we do this on delete button we have the same feature than activated button no ?

**Comment by NtsikaMngoma** [comment]
No, it makes a full delete of the row of that user.
It's not archived for future reference.

**Comment by nicolas63** [comment]
yes it's actual behavior but if we change this we have the same thing than "activated" button ? The deactivation button is not enough to archive your users ?
