### ISSUE TITLE
Dockerfile for the jhipster dotnetcore application is missing.

### ISSUE THREAD

**Issue by bhawdeadlydan** [jhipster/jhipster-dotnetcore#367]
As part of README it is mentioned that to create a docker container we should run the following command

docker build -f ./src/Jhipster/Dockerfile -t jhipster .

However as part of the latest commit the Dockerfile has been deleted.

##### **Overview of the issue**

The dockerfile to generate the app is missing.

##### **Motivation for or Use Case**

The Dockerfile should be part of the generated project to start the generated app effeciently.

##### **Reproduce the error**

Use the v6.10.1 of the jhipster dot net core blueprint to generate the project.

##### **JHipster Version(s)**

Jhipster v6.10.1
##### **JHipster configuration**

// UserAccount
enum  UserAccountType {
	SUPER_ADMIN,
	SUBSCRIBER_ADMIN,
    SUBSCRIBER_EDITOR,
    SUBSCRIBER_VIEWER
}

entity UserAccount {
	accountType UserAccountType
    accountName String required minlength(4)
}

// User UserAccount
relationship OneToOne {
  UserAccount{user} to User
}

// Projects
@filter
@paginate(pagination)
entity Project {
	projectName String required minlength(4)
    createdOn Instant
    createdBy String
    modifiedOn Instant
    modifiedBy String
    isDeleted Boolean
}

relationship OneToMany {
  UserAccount{project} to Project{account}
}

##### **Browsers and Operating System**

MacOS

-   [/ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by nicolas63** [comment]
Already fix by #364. Can you try with latest version ?
