### ISSUE TITLE
Full browsersync support like we have with Java backend

### ISSUE THREAD

**Issue by pdeoliveira** [jhipster/jhipster-dotnetcore#368]
##### **Full browsersync support testing local on Dev client using npm start on <project>/src/Sampledotnetcore/ClientApp like we have with Java backend.**

In the current release, it works only on the home page (anonymous), but fails trying to authenticate on login (DBUG 58309 --- [ 20] M.A.S.K.H.Internal.HttpsConnectionMiddleware : Failed to authenticate HTTPS connection.
System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslStream.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsServer(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsServerAsync>b__69_1(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware.InnerOnConnectionAsync(ConnectionContext context)

##### **Browsersync is very important on UI development for productivity**

Without browsersync, the developer needs to re-start the app every time he changes SCSS files (reload the page in the browser does not work), for example.

##### **Related issues or PR**

N/A

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by pedrocoliveira** [comment]
I also used npm --prefix ./src/Sampledotnetcore/ClientApp start, but with same error (Failed to authenticate HTTPS connection) on .NET Core log when trying to authenticate both with admin and user (monolithic app).

**Comment by nicolas63** [comment]
thanks for the feedback i need more time for investigation

**Comment by nicolas63** [comment]
it's due to webpack options i can fix it as workaround you can set in webpack.dev.js 

`target: ``http${options.tls ? 's' : ''}://localhost:5000``

by `http://localhost:5000`

**Comment by pdeoliveira** [comment]
> it's due to webpack options i can fix it as workaround you can set in webpack.dev.js
> 
> `target: `http${options.tls ? 's' : ''}://localhost:5000`
> 
> by `http://localhost:5000`

Thank you, but the problem was not with the code. When you load the application first time on the browser using https://localhost:5001 (or http that redirects to https), the browser shows a security screen, informing it's a non trusted source. After confirming it, the app is displayed and works. Only if you do this test and confirmation before using http://localhost:9000 it works (Chrome and Firefox - not Safari). If you do not confirm before, even with your suggested change, it doesn't work (Safari does not work even with screen confirmation and the changes on webpack.dev.js).

**Comment by ivanmonteiro** [comment]
> > it's due to webpack options i can fix it as workaround you can set in webpack.dev.js
> > `target: `http${options.tls ? 's' : ''}://localhost:5000`
> > by `http://localhost:5000`
> 
> Thank you, but the problem was not with the code. When you load the application first time on the browser using https://localhost:5001 (or http that redirects to https), the browser shows a security screen, informing it's a non trusted source. After confirming it, the app is displayed and works. Only if you do this test and confirmation before using http://localhost:9000 it works (Chrome and Firefox - not Safari). If you do not confirm before, even with your suggested change, it doesn't work (Safari does not work even with screen confirmation and the changes on webpack.dev.js).

@pdeoliveira I see that the issue is closed and probably solved, but if it can be of any help for someone facing problems with the https certificate. I have not had the time to test this issue, but I'll leave some references here and (hopefully) help someone:

https://docs.microsoft.com/pt-br/aspnet/core/security/enforcing-ssl?view=aspnetcore-3.1&tabs=visual-studio#trust-the-aspnet-core-https-development-certificate-on-windows-and-macos
https://www.hanselman.com/blog/DevelopingLocallyWithASPNETCoreUnderHTTPSSSLAndSelfSignedCerts.aspx
