### ISSUE TITLE
Change Data namespace to Infrastructure.Data

### ISSUE THREAD

**Issue by ivanmonteiro** [jhipster/jhipster-dotnetcore#379]
##### **Overview of the feature request**

ApplicationDatabaseContext and related classes were moved to Infrastructure project at "Data" subfolder. 
But current namespace is ProjectName.Data and should be changed to ProjectName.Infrastructure.Data to reflect this change.

![image](https://user-images.githubusercontent.com/891084/94312942-3f25d080-ff54-11ea-93b9-a6f32105d7c1.png)

![image](https://user-images.githubusercontent.com/891084/94313439-1baf5580-ff55-11ea-8239-ca55b62431cb.png)
![image](https://user-images.githubusercontent.com/891084/94313466-28cc4480-ff55-11ea-81e6-5a63c6e49551.png)

##### **Related issues or PR**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by austin0150** [comment]
I would like to work on this if that's ok

**Comment by nicolas63** [comment]
Sure !

**Comment by ivanmonteiro** [comment]
> I would like to work on this if that's ok

@austin0150 If you need help dont be afraid to ask!

**Comment by austin0150** [comment]
Well, @ivanmonteiro, I believe I was able to refactor the code properly, but I'm having an issue attempting to use the blueprint locally, and trying to generate an application with jhipster, to test the changes.
Would you be able to verify that I have taken the appropriate steps?

1. Install what is needed; Java11, NodeJS(LTS), Installing Jhipster with (npm install -g generator-jhipster), and then installing Yeoman with (npm install -g yo)
2. cd into the blueprint (.yo-rc has it named as generator-jhipster-blueprint) with my changes, 
3. run npm link
4. cd into a folder for the test-app
5. run npm link generator-jhipster-dotnetcore
6. run jhipster -d --blueprint dotnetcore

I follow through the proccess, but the resulting app does not include my changes and I cannot tell if I am using my local version of the blueprint.

**Comment by nicolas63** [comment]
@austin0150 this step is good, you can verify after npm link generator-jhipster-dotnetcore you have a folder node_modules with a folder generator-jhipster-dotnetcore verify if your code is in this folder

**Comment by austin0150** [comment]
@nicolas63 That helped, thank you, I found where I was going wrong.
Just for clarification, this issue applies to both the 'server' generator and the 'entity-server' generator, correct?

**Comment by nicolas63** [comment]
Yes
