### ISSUE TITLE
Update the Docker build

### ISSUE THREAD

**Issue by danielpetisme** [jhipster/jhipster-dotnetcore#38]
Verify the docker build is following the recommmandations of
https://dev.to/dotnet/how-you-can-dockerize-a-net-core-app-4h96?ocid=AID2417799_TWITTER_oo_spl100000934921659

**Comment by ivanmonteiro** [comment]
From what I see, It seems to be following the recommendations.  With an extra step of installing nodejs since it is required for the client app.
