### ISSUE TITLE
Remove in extension method @this and rename parameter 

### ISSUE THREAD

**Issue by nicolas63** [jhipster/jhipster-dotnetcore#383]
##### **Overview of the feature request**

We have lot of extension method who use @this 
` public static IServiceCollection AddWebModule(this IServiceCollection @this)`

@this is not the standard for the extension method we can rename to service or other pertinent name depending on the case 

##### **Related issues or PR**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by nicolas63** [comment]
Need to be remove in DbContextExtensions and in MvcStartup.cs

**Comment by michelvosje** [comment]
Let me take a look.
