### ISSUE TITLE
Bump nuget dependencies

### ISSUE THREAD

**Issue by nicolas63** [jhipster/jhipster-dotnetcore#384]
##### **Overview of the feature request**

Bump nuget dependencies (AutoMapper, Serilog, Scutor, etc ) 

##### **Related issues or PR**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by EnmanuelReyes** [comment]
Hi, I can help with this ticket.

I didn't find anything related to **Scutor**, is that correct?

Do you want any other dependencies to be updated?

**Comment by ivanmonteiro** [comment]
> Hi, I can help with this ticket.
> 
> I didn't find anything related to **Scutor**, is that correct?
> 
> Do you want any other dependencies to be updated?

Those dependencies are of the generated project, so the first step would be to check the sample project at https://github.com/jhipster/jhipster-sample-app-dotnetcore (or generate a new dotnet project using jhipster).

Then check the dotnet projects (main project, test project, domain, services, crosscut, etc....) nuget dependencies for outdated nuget packages.

Then, update the templates (Project.csproj.ejs) located at the 'server' generator with the new versions of the packages, check folder below:
https://github.com/jhipster/jhipster-dotnetcore/tree/master/generators/server/templates/dotnetcore/src

**Comment by EnmanuelReyes** [comment]
Thanks @ivanmonteiro, I will take this issue.
