### ISSUE TITLE
[CI] Add github actions ci in generated project 

### ISSUE THREAD

**Issue by nicolas63** [jhipster/jhipster-dotnetcore#386]
##### **Overview of the feature request**

[CI] Add github actions ci in generated project 

##### **Related issues or PR**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by rohan2734** [comment]
hi i would like to work on this issue.

**Comment by rohan2734** [comment]
hi can you help me with this, what script do i need to run for starting this app? , since i have to mention it in the yml file.

**Comment by rohan2734** [comment]
@nicolas63  can you tell me the list of jobs that i can perform in the yml file? , or is it there  in README.md?

**Comment by nicolas63** [comment]
Today our generated project is like (https://github.com/jhipster/jhipster-sample-app-dotnetcore) without ci. 
When the application was generated we need to add ci for build and test the application ( dotnet buid  and dotnet test for the server and npm test for the client )

Step for this issue : 
-  [ ] create the workflow 
-  [ ] create in the generator a ci-cd folder and ask the user he wants to add ci with github ( you can take look at https://github.com/jhipster/generator-jhipster/blob/master/generators/ci-cd/prompts.js) 
-  [ ] tansform the workflow in template ( you can take look at https://github.com/jhipster/generator-jhipster/blob/master/generators/ci-cd/templates/github-ci.yml.ejs) 
-  [ ] and finally write files  ( you can take look at https://github.com/jhipster/generator-jhipster/blob/master/generators/ci-cd/index.js)

**Comment by rohan2734** [comment]
@nicolas63  how to create a work flow
- when i searched it in google, github docs is opened, and it tells to go to ```actions```
- after that we need to create a workflow, example:
![image](https://user-images.githubusercontent.com/58523134/94667128-04dd7a00-032c-11eb-87aa-f07c8591577c.png)

-but in your actions, there are lready workflows setup and there is no option to create one.
![image](https://user-images.githubusercontent.com/58523134/94667204-20488500-032c-11eb-954c-e12010dce817.png)

- I am stuck at the first step itself, please explain.
