### ISSUE TITLE
[CI] Add gitlab ci in generated project 

### ISSUE THREAD

**Issue by nicolas63** [jhipster/jhipster-dotnetcore#387]
##### **Overview of the feature request**

Add gitlab ci in generated project 

##### **Related issues or PR**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by rohan2734** [comment]
hi i would like to work on this issue.

**Comment by nicolas63** [comment]
> hi i would like to work on this issue.

Nice

**Comment by rohan2734** [comment]
> Nice

so you can assign me this , and i will start working on it.

**Comment by nicolas63** [comment]
done

**Comment by nicolas63** [comment]
if you have any question don't hesitate to ask me

**Comment by rohan2734** [comment]
@nicolas63  sure

**Comment by rohan2734** [comment]
- @nicolas63  added ```.gitlab-ci.yml``` , in  https://github.com/rohan2734/jhipster-dotnetcore/tree/rohan2734
- Please check it, i never worked on this ci.
- please suggest me , and tell the changes ,and
- please guid me too

**Comment by nicolas63** [comment]
You are not in the right direction (same for #386 ) 
This project is a code generator, and this repo have already a ci (https://github.com/jhipster/jhipster-dotnetcore/tree/master/.github/workflows)
The goal of this issue is to generate .gitlab-ci.yml in generated project. so you don't need to install jhipster just run command for build and test with dotnet and npm) .
You can try this by create a project in gitlab with a generated app like https://github.com/jhipster/jhipster-sample-app-dotnetcore

When your ci work we need to add in generation process like the main generator (https://github.com/jhipster/generator-jhipster/tree/master/generators/ci-cd) I can help you on this step

**Comment by rohan2734** [comment]
@nicolas63  okay i will try

**Comment by rohan2734** [comment]
- @nicolas63  this is the thing which i have tried, 
- please check https://github.com/rohan2734/jhipster-dotnetcore/tree/rohan2734/.github/workflows

**Comment by nicolas63** [comment]
You can't put the gitlab-ci.yml here (it's the ci of the generator) 

Take exemple on this ( https://github.com/jhipster/generator-jhipster/tree/master/generators/ci-cd) 
We need the same thing in this generator 

In your gitlab-ci you use directly command with this the runner need to have dotnet and npm. I prefer use docker image like (https://stackoverflow.com/questions/57292553/how-to-set-up-a-build-and-test-pipeline-for-asp-net-core-web-application-with-an)

**Comment by rohan2734** [comment]
>You can't put the gitlab-ci.yml here (it's the ci of the generator)

so where should i keep it?

**Comment by nicolas63** [comment]
You must put this file in generator/ci-cd/template

**Comment by nicolas63** [comment]
You can use image: mcr.microsoft.com/dotnet/core/sdk:3.1

**Comment by rohan2734** [comment]
@nicolas63  raised a PR  please check.
