### ISSUE TITLE
[CI-CD] Build and publish docker image with github actions 

### ISSUE THREAD

**Issue by nicolas63** [jhipster/jhipster-dotnetcore#390]
##### **Overview of the feature request**

Build and publish docker image with github actions 

##### **Related issues or PR**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by ThirumlaDevi** [comment]
@nicolas63 I would like to help you with this github workflow. I am thinking of writing a workflow, which should be able to build and push docker image to [jhipster docker hub](https://hub.docker.com/r/jhipster/jhipster/), when a PR is merged.
Can you please assign this to me ?

**Comment by nicolas63** [comment]
This issue is for the generated application but like you suggest we can also do the same thing for the generator. You can start to read this https://github.com/jhipster/jhipster-dotnetcore/blob/main/README.md#using-docker. Do you need more informations ?

**Comment by ThirumlaDevi** [comment]
@nicolas63 Thank you for providing the needed informations. I hope that PR https://github.com/jhipster/jhipster-dotnetcore/pull/425 fixes this issue :) 
Please do let me know if you have any issues with the above PR.
