### ISSUE TITLE
New Bug introduce on sonar 

### ISSUE THREAD

**Issue by nicolas63** [jhipster/jhipster-dotnetcore#434]
##### **Overview of the issue**

https://sonarcloud.io/project/issues?id=jhipster_jhipster-sample-app-dotnetcore&resolved=false&types=BUG

##### **Related issues**

intruduced after https://github.com/jhipster/jhipster-dotnetcore/pull/433

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by ivanmonteiro** [comment]
I'm working on this
