### ISSUE TITLE
Does not create a .sln file

### ISSUE THREAD

**Issue by vraravam** [jhipster/jhipster-dotnetcore#44]
When I tried to generate a new scaffold, it takes me through the wizard, but at the end, I could not find a `.sln` file. Without this file, importing into Visual Studio seems incomplete/incorrect.

**Comment by ivanmonteiro** [comment]
Maybe you dont have the dotnet core cli installed on your system or it is not in your PATH

**Comment by danielpetisme** [comment]
Not active.
Closing
