### ISSUE TITLE
Bad Gateway 502 microservice gateway entity

### ISSUE THREAD

**Issue by manisi** [jhipster/jhipster-dotnetcore#446]
Hello,
getAllFoo Entity List:
Erorr: Bad Gateway 502
http://localhost:5000/services/microservicefoo/api/foos

:::**_GateWay_** :::

##### **JHipster Version(s)**

```
/Users/developer
└── generator-jhipster@6.10.1 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "namespace": "Gateway",
    "applicationType": "gateway",
    "serviceDiscoveryType": "consul",
    "databaseType": "sqllite",
    "authenticationType": "jwt",
    "serverPort": "5000",
    "prodDatabaseType": "mysql",
    "jhipsterVersion": "6.10.3",
    "baseName": "Gateway",
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1604746265880,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [
      {
        "name": "generator-jhipster-dotnetcore",
        "version": "1.1.2"
      }
    ],
    "enableTranslation": false,
    "blueprints": [
      {
        "name": "generator-jhipster-dotnetcore",
        "version": "1.1.2"
      }
    ],
    "promptValues": {
      "microservicePath": "../microserviceFoo"
    }
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

:::**_MicroServiceFoo_**:::

##### **JHipster Version(s)**

```
/Users/developer
└── generator-jhipster@6.10.1 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "namespace": "MicroserviceFoo",
    "applicationType": "microservice",
    "serviceDiscoveryType": "consul",
    "databaseType": "sqllite",
    "authenticationType": "jwt",
    "serverPort": "5004",
    "prodDatabaseType": "mysql",
    "jhipsterVersion": "6.10.3",
    "creationTimestamp": 1604746101127,
    "baseName": "MicroserviceFoo",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [
      {
        "name": "generator-jhipster-dotnetcore",
        "version": "1.1.2"
      }
    ],
    "enableTranslation": false,
    "clientPackageManager": "npm",
    "blueprints": [
      {
        "name": "generator-jhipster-dotnetcore",
        "version": "1.1.2"
      }
    ],
    "skipClient": true,
    "skipUserManagement": true
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Foo {
  name String
}
dto Foo with mapstruct
service Foo with serviceImpl
microservice Foo with MicroserviceFoo
clientRootFolder Foo with MicroserviceFoo

</pre>
</details>

##### **Environment and Tools**

openjdk version "1.8.0_242"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_242-b08)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.242-b08, mixed mode)

git version 2.20.1

node: v13.7.0

npm: 6.14.8

yeoman: 3.1.1

yarn: 1.21.1

Docker version 19.03.13, build 4484c46d9d

docker-compose version 1.27.4, build 40524192

identical .jhipster/Foo.json

**Comment by nicolas63** [comment]
Can you give me for information ?

**Comment by manisi** [comment]
Gateway ui (Foo Entity) when call data from  microserviceFoo this error
rise I think route from gateway to microserviceFoo  is incorrect

**Comment by manisi** [comment]
@nicolas63  Hello , 
I think removing this phrase '/service' ,( UpstreamPathTemplate": "/service/microservice/api/bars/{everything}")  from the template generatore will be removed.
Thanks to you
