### ISSUE TITLE
Remove duplicate call to SaveChangesAsync()

### ISSUE THREAD

**Issue by ivanmonteiro** [jhipster/jhipster-dotnetcore#459]
##### **Overview of the issue**

SaveChangesAsync() is being callled twice for create/update:
At the entity service/controller
And at  the entity repository method CreateOrUpdateAsync

##### **JHipster Version(s)**

Remove call to SaveChangesAsync() at the entity's repository method CreateOrUpdateAsync at the template file `EntityRepository.cs.ejs`.

##### **Browsers and Operating System**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by nicolas63** [comment]
@ivanmonteiro Do we need to address this before 2.0 ?

**Comment by ivanmonteiro** [comment]
> @ivanmonteiro Do we need to address this before 2.0 ?

The second call to SaveChangesAsync is redundant, so I dont think it will be a problem.

There are two options for this:
Remove call to SaveChangesAsync() at the entity's repository method CreateOrUpdateAsync at the template file EntityRepository.cs.ejs.

or

Remove call to SaveChangesAsync() at controller and service.

**Comment by nicolas63** [comment]
I think it's the service/controller that should call Save

**Comment by ivanmonteiro** [comment]
I have just noticed that DeleteAsync method at GenericRepository also calls SaveChangesAsync
