### ISSUE TITLE
Dotnet publish fails when using release configuration

### ISSUE THREAD

**Issue by ivanmonteiro** [jhipster/jhipster-dotnetcore#460]
##### **Overview of the issue**

Error when running the command `dotnet publish --verbosity normal -c Release -o ./app/out ./JhipsterSampleApplication.csproj` while following the generated project's build instructions for production:

##### **Reproduce the error**

Using main version of jhipsternet generator, create an application with jhipster --blueprint dotnet-core command.
And follow readme instructions (reproduced below) to build for production:

Generated project's readme instructions:
```
## Building for production

To build the arifacts and optimize the JhipsterSampleApplication application for production, run:

    cd ./src/JhipsterSampleApplication
    rm -rf ./src/JhipsterSampleApplication/wwwroot
    dotnet publish --verbosity normal -c Release -o ./app/out ./JhipsterSampleApplication.csproj

The `./src/JhipsterSampleApplication/app/out` directory will contain your application dll and its depedencies.

This will concatenate and minify the client CSS and JavaScript files. It will also modify `index.html` so it references these new files.
```

##### **Suggest a Fix**

It seems that this error occurs because `npm install` is not run as a build step when using the Release configuration of `dotnet publish` command. 

Since the dotnet publish uses the Release configuration, the ClientApp is not installed and this error occurs:
```
  (RunWebPack destino) -> 
     EXEC : error : Cannot find module 'workbox-webpack-plugin' [C:\Users\random\projetos\jhipsternet-heroku-ef5\src\JhipsterSampleApplication\JhipsterSampleApplication.csproj]
     C:\Users\random\projetos\jhipsternet-heroku-ef5\src\JhipsterSampleApplication\JhipsterSampleApplication.csproj(84,9): error MSB3073: O comando "npm run webpack:prod" foi encerrado com o código 1.
```

On further investigation and with help of @maznag and @nicolas63 it seems that the csproj's configuration has a condition that only runs `npm install` for Debug configuration.
```
    <Target Name="NpmInstall" BeforeTargets="Build" Condition=" '$(Configuration)' == 'Debug' And !Exists('node_modules') ">
        <!-- Ensure Node.js is installed -->
        <Exec WorkingDirectory="$(SpaRoot)" Command="node --version" ContinueOnError="true">
            <Output TaskParameter="ExitCode" PropertyName="ErrorCode" />
        </Exec>
        <Error Condition="'$(ErrorCode)' != '0'" Text="Node.js is required to build and run this project. To continue, please install Node.js from https://nodejs.org/, and then restart your command prompt or IDE." />
        <Message Importance="high" Text="Restoring dependencies using 'npm'. This may take several minutes..." />
        <Exec WorkingDirectory="$(SpaRoot)" Command="npm install" />
    </Target>

```

A possible fix is to remove the condition:
```
    <Target Name="NpmInstall" BeforeTargets="Build" Condition="  !Exists('node_modules') ">
```

Or change it to OR condition:
```
    <Target Name="NpmInstall" BeforeTargets="Build" Condition=" '$(Configuration)' == 'Debug' Or !Exists('node_modules') ">
```

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by nicolas63** [comment]
I prefer first option
