### ISSUE TITLE
Extract JHipsterNet, generate a nuget and use it as dependencies on generated app

### ISSUE THREAD

**Issue by nicolas63** [jhipster/jhipster-dotnetcore#49]

**Comment by ivanmonteiro** [comment]
I think it is a step in the right direction. And when a stable version is realeased I think It would be nice to have this code in a separete nuget package as you suggested.

**Comment by ivanmonteiro** [comment]
Would a new github repository be needed for this?

**Comment by nicolas63** [comment]
Yes here (https://github.com/jhipster/jhipster-net)

**Comment by nicolas63** [comment]
i have publish code from JhipsterNet, i publish the nuget soon

**Comment by nicolas63** [comment]
publication done (https://www.nuget.org/packages/JHipsterNet.Web/ and https://www.nuget.org/packages/JHipsterNet.Core/)

**Comment by ivanmonteiro** [comment]
> publication done (https://www.nuget.org/packages/JHipsterNet.Web/ and https://www.nuget.org/packages/JHipsterNet.Core/)

Wow, well done

**Comment by nicolas63** [comment]
I'm doing the modification on the generator 😃
