### ISSUE TITLE
Does not generate react ui code

### ISSUE THREAD

**Issue by vraravam** [jhipster/jhipster-dotnetcore#57]
I have used jhipster on prior projects to generate java backend with react ui.

When I tried to generate a new project for dotnetcore - it only generates angular - not react.

**Comment by danielpetisme** [comment]
Hi.

You are right react is one of the frontend option in the "official"
generator.
But... As for now the dotnet blueprint only covers Angular.
Feel free to contribute if it's important to you, it's not a lot of work, I
can explain what has to be done.

**Comment by ProIcons** [comment]
What has to be done

**Comment by danielpetisme** [comment]
The main issue is that there is no easy ways to customize the client files generation output path. I used a silly workaround for Angular so we can either update the code here:
https://github.com/jhipster/jhipster-dotnetcore/blob/master/generators/entity-client/files.js

or wait for the PR which introduce a way to control the generation 
https://github.com/jhipster/generator-jhipster/pull/11337

**Comment by nicolas63** [comment]
@mshima in the file-angular.js or file-react.js the generator use constant like : 

```
/* Constants use throughout */
const MAIN_SRC_DIR = constants.CLIENT_MAIN_SRC_DIR;
const TEST_SRC_DIR = constants.CLIENT_TEST_SRC_DIR;
const ANGULAR_DIR = constants.ANGULAR_DIR;

....

 sass: [
        {
            path: MAIN_SRC_DIR,
            templates: ['content/scss/_bootstrap-variables.scss', 'content/scss/global.scss', 'content/scss/vendor.scss']
        },
        {
            condition: generator => generator.enableI18nRTL,
            path: MAIN_SRC_DIR,
            templates: ['content/scss/rtl.scss']
        }
    ],

```

How to override value with outputPathCustomizer ? 
I have test to add something like this : 
```
 this.options.outputPathCustomizer = paths => (paths ? paths.replace(/^src\/main\/webapp([/$])/, 'src/main/webapp2$1') : undefined);  
   ```
but only the folder webapp2 was created and file genrerated are in webapp folder

**Comment by mshima** [comment]
Should be put at `cli/cli/sharedOptions.js`:
```
{
    outputPathCustomizer: paths => (paths ? paths.replace(/^src\/main\/webapp([/$])/, 'src/main/webapp2$1') : undefined);
}
```
It will be shared between every generator.

https://github.com/jhipster/generator-jhipster/blob/master/test/templates/blueprint-cli/cli/sharedOptions.js

**Comment by nicolas63** [comment]
@mshima yes i have do this, the folder webapp2 was created but the generated files is in /src/main/webapp because in file-angular.js this contant is used ```const MAIN_SRC_DIR = constants.CLIENT_MAIN_SRC_DIR;```

**Comment by mshima** [comment]
> @mshima yes i have do this, the folder webapp2 was created but the generated files is in /src/main/webapp because in file-angular.js this contant is used `const MAIN_SRC_DIR = constants.CLIENT_MAIN_SRC_DIR;`

@nicolas63 I think I missed what do you want to achieve.
Do you have an code example/branch?
If you want to apply to a path string then you should run:
`const dest = this.destinationPath('src/main/webapp/foo')`
dest value should became `src/main/webapp2/foo`.

**Comment by nicolas63** [comment]
@mshima in the dotnet generator we override destination path like this : 

```
for (let i = 0, blocks = Object.keys(angularFiles); i < blocks.length; i++) {
    const blockKey = blocks[i];
    files[blockKey] = [];
    for (let j = 0, blockTemplates = angularFiles[blocks[i]]; j < blockTemplates.length; j++) {
        const blockTemplate = blockTemplates[j];
        const udpatedBlockTemplate = {};
        let previousPath = '';
        if (blockTemplate.path) {
            previousPath = blockTemplate.path;
            udpatedBlockTemplate.path = '';
        }
        if (blockTemplate.condition) {
            udpatedBlockTemplate.condition = blockTemplate.condition;
        }
        udpatedBlockTemplate.templates = blockTemplate.templates.map(templateObj => {
            let file = '';
            if (typeof templateObj === 'string') {
                file = templateObj;
            } else if (typeof templateObj.file === 'string') {
                file = templateObj.file;
            } else if (typeof templateObj.file === 'function') {
                file = templateObj.file(generator);
            }
            const updatedTemplateObj = {
                file: `${previousPath}/${file}`,
                renameTo: generator => `${fileDestinationMapping[blockKey](generator)}/${file}`
            };
            if (templateObj.method) {
                updatedTemplateObj.method = templateObj.method;
            }
            return updatedTemplateObj;
        });
        files[blockKey].push(udpatedBlockTemplate);
    }
}
```

I want refactor this for use outputPathCustomizer

You can see my code here https://github.com/nicolas63/jhipster-dotnetcore/blob/ReactAsfront/generators/client/index.js

**Comment by nicolas63** [comment]
The goal is to generate files in /src/MyApp/ClientApp rather than /src/main/webapp

**Comment by mshima** [comment]
You should update generator-jhispter dependency to 6.8.0

**Comment by nicolas63** [comment]
it's already up to date

**Comment by mshima** [comment]
> it's already up to date

you are right I confused.

**Comment by mshima** [comment]
Worked for me:
```
 create src/JHipsterNet/Logging/LoggerNameEnricher.cs
   create src/JHipsterNet/JHipsterNet.csproj
   create docker/telegraf/telegraf.conf
   create docker/kapacitor/config/kapacitor.conf
   create docker/influxdb/config/influxdb.conf
   create docker/grafana/data/dashboard/default-dashboard.yaml
   create SonarAnalysis.ps1
   create .eslintrc.json
   create .eslintignore
   create package.json
   create webpack/utils.js
   create webpack/webpack.common.js
   create webpack/webpack.dev.js
   create webpack/webpack.prod.js
   create postcss.config.js
   create webpack/logo-jhipster.png
   create .huskyrc
   create .lintstagedrc.js
   create src/main/webapp2/content/images/jhipster_family_member_0.svg
   create src/main/webapp2/content/images/jhipster_family_member_1.svg
   create src/main/webapp2/content/images/jhipster_family_member_2.svg
   create src/main/webapp2/content/images/jhipster_family_member_3.svg
   create src/main/webapp2/content/images/jhipster_family_member_0_head-192.png
   create src/main/webapp2/content/images/jhipster_family_member_1_head-192.png
```

Steps:
```
mkdir dotNet
cd dotNet
sudo npm install -g generator-jhipster@latest
npm install nicolas63/jhipster-dotnetcore#ReactAsfront
jhipster --blueprints dotnetcore
```

**Comment by nicolas63** [comment]
O_o ok so i investigate why it don't work for me.
thank you so much for your time and help !

**Comment by nicolas63** [comment]
@mshima the problem is only on windows due to windows format path
So i used the package "normalize-path" like : 
```
const normalize = require('normalize-path');
module.exports = {
    outputPathCustomizer: paths => (paths ? normalize(paths).replace(/^src\/main\/webapp\//g, 'src/main/webapp2/') : undefined)
};
```

**Comment by mshima** [comment]
> @mshima the problem is only on windows due to windows path format
> So i used the package "normalize-path" like :

You could try `path.win32.normalize` instead.
Maybe this could be applied upstream. I don't know.

**Comment by nicolas63** [comment]
yes maybe in generator-base.js ? 
```
 /**
     * Apply output customizer.
     *
     * @param {string} path - Path to customize.
     */
    applyOutputPathCustomizer(path) {
```

**Comment by mshima** [comment]
Yep.
Have you tested `path.win32.normalize`?

**Comment by nicolas63** [comment]
@mshima No, i have another problem.
There are still files in the folder /src/main/webapp

In think the problem is : 

In file-angular.js when we use method: 'processJs' 
```
               { file: 'home/home.module.ts', method: 'processJs' },
                { file: 'home/home.route.ts', method: 'processJs' },
                { file: 'home/home.component.ts', method: 'processJs' },
                { file: 'home/home.component.html', method: 'processHtml' },
```
 
the method is call and is transation is disable the path is not override 

```
function copyWebResource(source, dest, regex, type, generator, opt = {}, template) {
    if (generator.enableTranslation) {
        generator.template(source, dest, generator, opt);
    } else {
        renderContent(source, generator, generator, opt, body => {
            body = body.replace(regex, '');
            switch (type) {
                case 'html':
                    body = replacePlaceholders(body, generator);
                    break;
                case 'js':
                    body = replaceTitle(body, generator);
                    if (dest.endsWith('error.route.ts')) {
                        body = replaceErrorMessage(body, generator);
                    }
                    break;
                case 'jsx':
                    body = replaceTranslation(body, generator);
                    break;
                default:
                    break;
            }
            generator.fs.write(dest, body);
        });
    }
}
```

I'am not sure. what do you think?

**Comment by mshima** [comment]
> I'am not sure. what do you think?

This one looks a bug to me.

**Comment by mshima** [comment]
@nicolas63 can you test with https://github.com/jhipster/generator-jhipster/tree/output_customizer?

**Comment by nicolas63** [comment]
> 
> 
> @nicolas63 can you test with https://github.com/jhipster/generator-jhipster/tree/output_customizer?

it's works !  there are just the src/main/webapp who was created but is empty. I don't know why

**Comment by nicolas63** [comment]
@mshima i have try without ```const normalize = require('normalize-path'); ``` but it doesn't work

**Comment by mshima** [comment]
> normalize-path

Just tried myself. `path.win32.normalize` doesn't do the job.
We should probably add normalize-path or slash.

**Comment by nicolas63** [comment]
For empty folder i have add a second regex :

 ```
const normalize = require('normalize-path');
module.exports = {
    outputPathCustomizer: [
        paths => (paths ? normalize(paths).replace(/^src\/main\/webapp([\/$])/, 'src/main/webapp2$1') : undefined),
        paths => (paths ? normalize(paths).replace(/^src\/main\/webapp$/, 'src/main/webapp2') : undefined)
    ]
};
```

So all works for me, if you could add normalize in main generator that would be great. 
Thanks again for your help !

**Comment by mshima** [comment]
Try this:
```
module.exports = {
   outputPathCustomizer: [
       paths => paths ? normalize(paths) : paths,
       paths => paths ? paths.replace(/^src\/main\/webapp(\/|$)/, 'src/main/webapp2$1')
   ]
};
```

**Comment by nicolas63** [comment]
> 
> 
> Try this:
> 
> ```
> module.exports = {
>    outputPathCustomizer: [
>        paths => paths ? normalize(paths) : paths,
>        paths => paths ? paths.replace(/^src\/main\/webapp(\/|$)/, 'src/main/webapp2$1')
>    ]
> };
> ```

it works ! thanks

**Comment by mshima** [comment]
I missed `: paths`.

Probably you saw.

**Comment by nicolas63** [comment]
> 
> 
> I missed `: paths`.
> 
> Probably you saw.

yes, no problem thanks
