### ISSUE TITLE
Upgrade Entity Framework packages for Oracle compatibility

### ISSUE THREAD

**Issue by ivanmonteiro** [jhipster/jhipster-dotnetcore#614]
##### **Overview of the issue**

Entity Framework packages are fixed. It is using the same version (v5.0.0) of the asp.net core. 

https://github.com/jhipster/jhipster-dotnetcore/blob/0348960d5888f47d9a5244a5be23b517c7843403/generators/server/templates/dotnetcore/src/Directory.Build.targets#L3

https://github.com/jhipster/jhipster-dotnetcore/blob/0348960d5888f47d9a5244a5be23b517c7843403/generators/server/templates/dotnetcore/src/Directory.Build.targets#L92

Oracle packages needs EF >= v5.0.1.

My suggestion is to upgrade Entity Framework packages. 
Entity Framework does not need to be the **same** version as the .Net Framework and EF can be upgraded.

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by nicolas63** [comment]
Exactly i think you have right we can use two variables
