### ISSUE TITLE
Fix npm packaging

### ISSUE THREAD

**Issue by nicolas63** [jhipster/jhipster-dotnetcore#71]
The npm package was not publish alter build see https://www.npmjs.com/package/generator-jhipster-dotnetcore

**Comment by danielpetisme** [comment]
I released
https://www.npmjs.com/package/generator-jhipster-dotnetcore

Can you I have a weird issue locally.

**Comment by nicolas63** [comment]
Thanks :smiley: ! I'm testing as soon as possible

**Comment by nicolas63** [comment]
I have test it the project generation is ok but i have an issue with npm install during the generation. Is the same issue ?

**Comment by danielpetisme** [comment]
Fix #85
