### ISSUE TITLE
Add support for Service Discovery and Config Server

### ISSUE THREAD

**Issue by sergrdz** [jhipster/jhipster-dotnetcore#73]
Like jhipster generator these features could be added with the library https://steeltoe.io/

**Comment by danielpetisme** [comment]
Could you detail what you want to do please.

From what I see, more and more projects are delegating discovery and configuration to an underlying infra service (like k8s).
On Java side, Netflix was a pioneer and opensource great projects which are not very active now...

What's your vision on it?

**Comment by sergrdz** [comment]
The idea is to add functionality for registration and discovery of services as the java version does. Using Eureka Register or Consul.

If we do it this way we could have communication between Java and NETCore microservices.

Therefore the microservices generated in NETCore should be able to integrate with Eureka Registry or Consul.

I have tested the library https://steeltoe.io/service-discovery/get-started/eureka, registration is done properly and the NETCore microservice has the following possibilities:
1. It can be invoked by other java generated microservices and gateways.
2. You can invoke other microservices generated in Java and NETCore.

I have not reviewed in detail is how to do the routing from the gateway. I have gone through a bit of the library documentation https://threemammals.com/ocelot, but have not had time to test.
