### ISSUE TITLE
couldn't Save relationships with dto mapstruct 

### ISSUE THREAD

**Issue by gatity** [jhipster/jhipster-dotnetcore#787]
##### **Overview of the issue**

When I import entities by JDL with  "dto * with mapstruct" set in the JDL,one to one and one to many relationships does not save in database, 
I'm using the version 7.0.1 of jhipster.net with angular as the frontend.
I inserted a jdl file like below and I couldn't save none of the relations between region and country and also country and location( I use angular UI to save them):
<pre>
entity Region {
	regionName String
}
entity Country {
	countryName String
}
entity Location {
	streetAddress String,
	postalCode String,
	city String,
	stateProvince String
}
relationship OneToOne {
	Country{region} to Region
}
relationship OneToOne {
	Location{country} to Country
}
dto * with mapstruct
</pre>

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by ivanmonteiro** [comment]
I think that with jhipster v7 the client sends the full entity relationships to the server... But the dto implementation has only the relationship id. 
On the generated app I changed the dto relationship to use the other entity Dtos and It seems to work.

**Comment by ivanmonteiro** [comment]
I'll try a PR this weekend

**Comment by ivanmonteiro** [comment]
The relationships ids at the DTO are never being set. 
Example:
```
 public class ProductDto
    {
        public long Id { get; set; }
        public string Sku { get; set; }
        ...
        public long SupplierId { get; set; }
    }
```
SupplierId is never set. The client (angular) sends full relationship for related entity, not only the ID:
```
{
   id: 1,
   sku: "abcde",
   supplier: {
      id: 22
      supplierName: "ABC"
   }
```

**Comment by nicolas63** [comment]
@ivanmonteiro where are you on this issue  ?

**Comment by nicolas63** [comment]
this issue is due to https://github.com/jhipster/generator-jhipster/issues/12707

**Comment by ivanmonteiro** [comment]
> @ivanmonteiro where are you on this issue ?

Sorry for the long time to reply.

I was able to reproduce the issue but I did not work on it. 

The solution seems straightforward:

Make dto relationships full objects like: 

Example:

```
    public class JobDto
    {

        public long Id { get; set; }

        public string JobTitle { get; set; }
        public long? MinSalary { get; set; }
        public long? MaxSalary { get; set; }

        public IList<PieceOfWorkDto> Chores { get; set; } = new List<PieceOfWorkDto>();

        // before:
        // public long? EmployeeId { get; set; }
        
        //after
        public EmployeeDto Employee { get ; set; }
    }
```

Some work will also be needed for the blazor client to adapt to those changes.

**Comment by nicolas63** [comment]
Already fixed
