### ISSUE TITLE
"Microfrontend is not defined" error when building with default options

### ISSUE THREAD

**Issue by HammNCheez** [jhipster/jhipster-dotnetcore#793]
##### **Overview of the issue**

When creating a project with the default options I am getting an error saying "microfrontend is not defined", the error message points to a file `..node_modules\generator-jhipster\generators\client\templtes\angular\package.json.ejs:169`

![jhipster net-error](https://user-images.githubusercontent.com/6722607/124531734-bc7c4c80-ddd4-11eb-8064-07c2e392268b.png)

##### **Motivation for or Use Case**
This prevents me from creating a project with the dotnetcore blueprint

##### **Reproduce the error**

clean install of jhipster and jhipster-dotnetcore and generate new project with default options

##### **Related issues**
I didn't see any other issues with the microfrontend keywords.

##### **Suggest a Fix**

All I can offer is the line in the error above. `..node_modules\generator-jhipster\generators\client\templtes\angular\package.json.ejs:169`

##### **JHipster Version(s)**

jhipster - v7.1.0 installed 
(but when running it tells me "update available: 7.1.0 (current: 7.0.1)" I have verified multiple times and not sure why its telling me that.

jhipster-dotnetcore - v3.0.1

##### **Browsers and Operating System**

OS: Windows 10 
I tried running through the windows command line as well as a bash shell and I get the same error.

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by ivanmonteiro** [comment]
Are you using the main version of jhipster.net (cloning the repo) or the npm version by running `npm install -g generator-jhipster-dotnetcore`?

**Comment by ivanmonteiro** [comment]
You might want to use v7,0,1 of the main jhipster generator with jhipster.net

**Comment by HammNCheez** [comment]
Downgrading did the trick. thanks for the help.

**Comment by nicolas63** [comment]
it's released 👍
