### ISSUE TITLE
Upgrade to JHipster 7.1

### ISSUE THREAD

**Issue by nicolas63** [jhipster/jhipster-dotnetcore#795]
##### **Overview of the feature request**

Upgrade to JHipster 7.1

##### **Related issues or PR**

#793 

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by ivanmonteiro** [comment]
Maybe after upgrading to jhipster 7.1.0 we finally merge the dependencies branch too?

**Comment by nicolas63** [comment]
Yes exactly

**Comment by nicolas63** [comment]
fix by https://github.com/jhipster/jhipster-dotnetcore/pull/798
