### ISSUE TITLE
Handle users/accounts with Mongo

### ISSUE THREAD

**Issue by Zenrac** [jhipster/jhipster-dotnetcore#803]
##### **Overview of the feature request**

After MongoDB support being added with #717, which allows to handle entities with MongoDB, the main missing feature is to handle Claims/Users/Accounts with Mongo. This could be done with [AspNetCore.Identity.Mongo](https://github.com/matteofabbri/AspNetCore.Identity.Mongo).

##### **Motivation for or Use Case**

This feature would allow to generate applications with Mongo that doesnt need a second in-memory database (SQLite) in order to manage Users/Account.

##### **Related issues or PR**

#96

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by enzo-ae** [comment]
Saw it a little too late, used a different library

#981

**Comment by nicolas63** [comment]
no worry, the other library is also good
