### ISSUE TITLE
Unable to run generated app - build with error: 'certFilename' does not exist in the current context

### ISSUE THREAD

**Issue by maznag** [jhipster/jhipster-dotnetcore#81]
Unable to run generated app using the latest version.
 
Program.cs(82,165): error CS0103: The name 'certFilename' does not exist in the current context 
 Program.cs(82,193): error CS0103: The name 'CertValidationCallback' does not exist in the current context TestDB.csproj

See last commit https://github.com/jhipster/jhipster-dotnetcore/commit/54cd2b3ab11f8856d7f411a36b17d8e057202889

**Comment by nicolas63** [comment]
Sorry is my bad, can you remove this part (new CertificateFileProvider(certFilename, String.Empty),CertValidationCallback)) 
I fix it as soon as possible
