### ISSUE TITLE
microfrontend is not defined ?

### ISSUE THREAD

**Issue by mohamedsogoba** [jhipster/jhipster-dotnetcore#817]
when i try to generate a new project i have this error at the end i don't understand? 
Please you can help me?
Unhandled promise rejection at:
ReferenceError: C:\Users\ME\AppData\Roaming\npm\node_modules\generator-jhipster\generators\client\templates\angular\package.json.ejs:169
    167| <%_ } _%>
    168|     "jest": "jest --coverage --logHeapUsage --maxWorkers=2 --config jest.conf.js",
 >> 169|     "start": "ng serve<% if (!microfrontend) { %> --hmr<% } %>",
    170|     "start-tls": "<%= clientPackageManager %> run webapp:dev -- --env.tls",
    171| <%_ if (skipServer) { _%>
    172|     "sonar": "sonar-scanner",

microfrontend is not defined

**Comment by nicolas63** [comment]
Yes, it's because the generator do not support jhipster v7.1 (deplicate issue :https://github.com/jhipster/jhipster-dotnetcore/issues/793)
I have added the support and i will release it soon https://github.com/jhipster/jhipster-dotnetcore/pull/798

**Comment by nicolas63** [comment]
it's released 👍
