### ISSUE TITLE
Creation of a new project fails

### ISSUE THREAD

**Issue by kamyarizadi** [jhipster/jhipster-dotnetcore#818]
After answering all question I have the following error during creation of new project:
Unhandled promise rejection at:
ReferenceError: C:\Users\izadiadmin\AppData\Roaming\npm\node_modules\generator-jhipster\generators\client\templates\angu
lar\package.json.ejs:169
    167| <%_ } _%>
    168|     "jest": "jest --coverage --logHeapUsage --maxWorkers=2 --config jest.conf.js",
 >> 169|     "start": "ng serve<% if (!microfrontend) { %> --hmr<% } %>",
    170|     "start-tls": "<%= clientPackageManager %> run webapp:dev -- --env.tls",
    171| <%_ if (skipServer) { _%>
    172|     "sonar": "sonar-scanner",

microfrontend is not defined

**Comment by nicolas63** [comment]
duplicate https://github.com/jhipster/jhipster-dotnetcore/issues/819
