### ISSUE TITLE
build error - No matching version found for generator-jhipster-dotnetcore@0.3.0

### ISSUE THREAD

**Issue by maznag** [jhipster/jhipster-dotnetcore#84]
can you publish the new npm package generator-jhipster-dotnetcore@0.3.0 ?

**Comment by ivanmonteiro** [comment]
Maybe @danielpetisme can publish to npm.
One suggestion is to configure Travis to publish the package to npm when a new tag is released. 
Documentation: https://docs.travis-ci.com/user/deployment/npm/

**Comment by nicolas63** [comment]
Yes, for the moment only @danielpetisme can publish. Configure travis for publish npm package is good solution :smile:

**Comment by ivanmonteiro** [comment]
This can be done adding this configuration .travis.yml 
![image](https://user-images.githubusercontent.com/891084/77234052-51c8e280-6b8a-11ea-9fc1-3ab818be165b.png)

And configuring travis with the environment variables NPM_EMAIL and NPM_API_TOKEN. I hope that this helps.

![image](https://user-images.githubusercontent.com/891084/77233988-f991e080-6b89-11ea-9f27-7476b8922260.png)

**Comment by pascalgrimaud** [comment]
I think it is not possible if you use OTP with NPM like me.

**Comment by danielpetisme** [comment]
I'll release the coming week.
I need to spend some time to understand how we could speed up or delegate releasing.

**Comment by pascalgrimaud** [comment]
@danielpetisme : just choose another releaser, then, we can contact Julien D. for adding him to the appropriate team in NPM organization.

**Comment by danielpetisme** [comment]
Actually the dotnet-blueprint is not part of the Jhipster npm organization.

I'll contact you to have a proper setup.

**Comment by wassimz** [comment]
@danielpetisme 
any update on the release date of the the Blueprint ?? Still have onlt the 0.2 version on npm repository

Thanks

**Comment by danielpetisme** [comment]
![Screenshot 2020-03-25 at 9 23 59 PM](https://user-images.githubusercontent.com/593564/77582063-11959700-6edf-11ea-932f-388f8f6543a2.png)

Here you go. 0.3.0 is out.
