### ISSUE TITLE
Required enum field causes compilation errors

### ISSUE THREAD

**Issue by ivanmonteiro** [jhipster/jhipster-dotnetcore#843]
##### **Overview of the issue**

At the generated project's EntityControllerIntTest.cs the enum field is assigned to null:
```
        [Fact]
        public async Task CheckStatusIsRequired()
        {
            var databaseSizeBeforeTest = await _entityRepository.CountAsync();

            // Set the field to null
            _entity.Status = null;
            ...
        }
}
```

Since enumeration fields are not nullable by default, this causes a compilation error. Also, setting it to 0 would defeat the purpose of the requiredness check of the test, since 0 will be transformed to a valid enumeration.

##### **Suggest a Fix**

It is possible to make the field nullable at the entity (and also at the DTO):
```
 public class Entity
 {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public long Id { get; set; }

        [Required]
        public Status? Status { get; set; }
}
```

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by nicolas63** [comment]
@ivanmonteiro Is this bug still present ?
