### ISSUE TITLE
How can i create microservices

### ISSUE THREAD

**Issue by galkzaz** [jhipster/jhipster-dotnetcore#849]
how can i create microservices and run it,I'm confused between jhipster --blueprints dotnetcore and jhipster import-jdl app.jdl which one shall I used
If I used  jhipster --blueprints dotnetcore it will create root foder baseName
If I used jhipster import-jdl app.jdl I faces many issues like
namespace created like namespace .Configuration
package name not used
how do i run the whole solution as in java
this is my jdl
/* Store gateway application */
application {
  config {
    baseName store
    applicationType gateway
    packageName mystore
    serviceDiscoveryType consul
    authenticationType oauth2
    prodDatabaseType mysql
    cacheProvider ehcache
    buildTool maven
    clientFramework angularX
    languages [en, ar-ly]
    
    testFrameworks [cypress, gatling, cucumber]
  }
  entities *
}

/* Invoice microservice application */
application {
  config {
    baseName invoice

    applicationType microservice
    packageName mystore
    serviceDiscoveryType consul
    authenticationType oauth2
    prodDatabaseType mysql
    buildTool maven
    serverPort 8081
    languages [en, ar-ly]

  }
  entities Invoice, Shipment
}

/* Notification microservice application */
application {
  config {
    baseName notification

    applicationType microservice
    packageName mystore
    serviceDiscoveryType consul
    authenticationType oauth2
    databaseType mongodb
    cacheProvider no
    enableHibernateCache false
    buildTool maven
    serverPort 8082
    languages [en, ar-ly]
  }
  entities Notification
}

/* Entiteis for store service */

/** Product sold by the Online store */
entity Product {
    name String required
    description String
    price BigDecimal required min(0)
    productSize Size required
    image ImageBlob
}

enum Size {
    S, M, L, XL, XXL
}

entity ProductCategory {
    name String required
    description String
}

entity Customer {
    firstName String required
    lastName String required
    gender Gender required
    email String required pattern(/^[^@\s]+@[^@\s]+\.[^@\s]+$/)
    phone String required
    addressLine1 String required
    addressLine2 String
    city String required
    country String required
}

enum Gender {
    MALE, FEMALE, OTHER
}

entity ProductOrder {
    placedDate Instant required
    status OrderStatus required
    code String required
}

enum OrderStatus {
    COMPLETED, PENDING, CANCELLED
}

entity OrderItem {
    quantity Integer required min(0)
    totalPrice BigDecimal required min(0)
    status OrderItemStatus required
}

enum OrderItemStatus {
    AVAILABLE, OUT_OF_STOCK, BACK_ORDER
}

relationship OneToOne {
    Customer{user(login) required} to User
}

relationship ManyToOne {
    OrderItem{product(name) required} to Product
}

relationship OneToMany {
    Customer{order} to ProductOrder{customer(email) required}, 
    ProductOrder{orderItem} to OrderItem{order(code) required}, 
    ProductCategory{product} to Product{productCategory(name)}
}

/* Entities for Invoice microservice */

entity Invoice {
    code String required
    date Instant required
    details String
    status InvoiceStatus required
    paymentMethod PaymentMethod required
    paymentDate Instant required
    paymentAmount BigDecimal required
    productOrderId Long required
}

enum InvoiceStatus {
    PAID, ISSUED, CANCELLED
}

enum PaymentMethod {
    CREDIT_CARD, CASH_ON_DELIVERY, PAYPAL
}

entity Shipment {
    trackingCode String
    date Instant required
    details String
}

relationship OneToMany {
    Invoice{shipment} to Shipment{invoice(code) required}
}

microservice Invoice, Shipment with invoice

/* Entities for notification microservice */

entity Notification {
    date Instant required
    details String
    sentDate Instant required
    format NotificationType required
    userId Long required
    productId Long required
}

enum NotificationType {
    EMAIL, SMS, PARCEL
}

microservice Notification with notification

/* General options */

service * with serviceClass
paginate Product, Customer, ProductOrder, Invoice, Shipment, OrderItem with pagination

**Comment by galkzaz** [comment]
I think the generator is not working with microservices and there is no docs or tutorial or example for this
I tried it my self but many problems and errors
I used Jhipster microservices with Java and its easy and well structured

**Comment by nicolas63** [comment]
can you try to create the microservice with cli rather than jdl ?

**Comment by galkzaz** [comment]
what do u mean by cli

**Comment by nicolas63** [comment]
oh yes sorry cli is not clear, if you create the microservice without jdl ( run jhipster --blueprint dotnetcore  and choose microservice) you have now one microservice, you can create a second microservice and next create a gateway. The gateway ask path of the microservcice and map route with ocelot and use consul as service discovery

**Comment by moodsharkh** [comment]
Hello I created a microservice and run Consul as a docker container and I can see the microservice on Consul. However, 
when I use "run jhipster --blueprint dotnetcore" and choose Microservice gateway there is no question about adding any microservice. am I missing something ?
If there is a sample Ocelot.json route entry that I can add.
I am using : JHipster.NET v3.6.0

![Screenshot 2022-06-21 161523](https://user-images.githubusercontent.com/31238209/174808384-6689ffb1-b10a-4945-a2d4-eecfaabf9848.png)

**Comment by moodsharkh** [comment]
My bad, it appeared when generating the entity on the API gateway
