### ISSUE TITLE
Add SonarQube

### ISSUE THREAD

**Issue by BananeGuimauve** [jhipster/jhipster-dotnetcore#9]
In order to evaluate the quality of the generated code, we need to add SonarQube in the generated application.

**Comment by ivanmonteiro** [comment]
I assume that the sonarqube's community edition (free) would be used, right?

**Comment by danielpetisme** [comment]
Yes. The idea would be to provide provide the SonarQube docker image in the generated project. If's already working with the Java project, I simply don't know how to configure Sonar to audit C# code.

**Comment by ivanmonteiro** [comment]
> Yes. The idea would be to provide provide the SonarQube docker image in the generated project. If's already working with the Java project, I simply don't know how to configure Sonar to audit C# code.

I'm setting up sonarqube locally and I must say that there are some pre-requisites that are not that straight forward, especially for .net developers. SonarScanner needs Java Runtime Environment installed. Also, to get the test/build measurements we also need a global install of sonarscanner fot .net core and it needs to be added to the path. 

One approach that I'm thinking to simplify all that is to move all of those pre-requisites to a docker container. What do you think? Other suggestions? Thanks

**Comment by pascalgrimaud** [comment]
closed by https://github.com/jhipster/jhipster-dotnetcore/pull/68
