### ISSUE TITLE
Failed generator – JHipster.NET v3.1.1

### ISSUE THREAD

**Issue by cvillami** [jhipster/jhipster-dotnetcore#918]
##### **Overview of the issue**

The generator does not start, and generates an error that I really cannot understand, much less solve. I have already removed the installation and reinstalled it and it still doesn't work.

##### **Motivation for or Use Case**

Generate an application of the type -> Monolithic application

##### **Reproduce the error**
[Error img](https://drive.google.com/file/d/17FADuxM-Ies-eYYQFNFhnh3XcMk4IfAn/view?usp=sharing)
 
>ERROR! Template file .npmrc was not found at /usr/local/lib/node_modules/generator-jhipster-dotnetcore/generators/client/templates/angular,/usr/local/lib/node_modules/generator-jhipster/generators/client/templates/angular

>Error: Template file .npmrc was not found at /usr/local/lib/node_modules/generator-jhipster-dotnetcore/generators/client/templates/angular,/usr/local/lib/node_modules/generator-jhipster/generators/client/templates/angular
    at /usr/local/lib/node_modules/generator-jhipster-dotnetcore/node_modules/generator-jhipster/generators/generator-base.js:2209:25
    at Array.map (<anonymous>)
    at /usr/local/lib/node_modules/generator-jhipster-dotnetcore/node_modules/generator-jhipster/generators/generator-base.js:2139:42
    at Array.map (<anonymous>)
    at /usr/local/lib/node_modules/generator-jhipster-dotnetcore/node_modules/generator-jhipster/generators/generator-base.js:2136:29
    at Array.map (<anonymous>)
    at module.exports.writeFilesToDisk (/usr/local/lib/node_modules/generator-jhipster-dotnetcore/node_modules/generator-jhipster/generators/generator-base.js:2135:45)
    at module.exports.writeFiles (/usr/local/lib/node_modules/generator-jhipster-dotnetcore/node_modules/generator-jhipster/generators/client/files-angular.js:521:15)
    at module.exports.writeFilesDotnetcore (/usr/local/lib/node_modules/generator-jhipster-dotnetcore/generators/client/index.js:118:47)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-jhipster-dotnetcore/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:1024:25)

>Unhandled promise rejection at:
ReferenceError: /usr/local/lib/node_modules/generator-jhipster/generators/client/templates/angular/package.json.ejs:23
    21|   "name": "<%= dasherizedBaseName %>",
    22|   "version": "0.0.1-SNAPSHOT",
    23|   "description": "<%= projectDescription %>",
    24|   "private": true,
    25|   "license": "UNLICENSED",
    26|   "cacheDirectories": [

projectDescription is not defined

##### **JHipster Version(s)**

> (base) cvillami@ToreToto poclg % npm ls --global generator-jhipster
/usr/local/lib
├─┬ generator-jhipster-dotnetcore@3.1.1
│ └── generator-jhipster@7.1.0
└── generator-jhipster@7.6.0

##### **JHipster configuration**

>? What is the base name of your application? Poclg
? What is your default C# namespace? Poclg
? Which *type* of application would you like to create? Monolithic application (recommended for simple projects)
? Besides JUnit and Jest, which testing frameworks would you like to use? Gatling
? On which port would like your server to run ? It should be unique to avoid port conflicts (choose http -> https=httpPort+1). 5000
? Do you want to use the CQRS design pattern? No
? Which database do you want to use SQLite in-memory
? Which *type* of authentication would you like to use? JWT authentication (stateless, with a token)
? Which *Framework* would you like to use for the client? Angular
WARNING! Could not fetch bootswatch themes from API. Using default ones.
? Would you like to use a Bootswatch theme (https://bootswatch.com/)? Default JHipster
? Would you like to enable internationalization support? Yes
? Please choose the native language of the application English
? Please choose additional languages to install Albanian
? Would you like to install other generators from the JHipster Marketplace? No

##### **Browsers and Operating System**
macOS version 12.2

**Comment by cvillami** [comment]
But now I have this error ->

> ERROR! Template file webpack/environment.js was not found at /Volumes/CWork/0--Original/jhipster/middle-santander/jhipster-dotnetcore-3.1.1/generators/client/templates/angular,/usr/local/lib/node_modules/generator-jhipster/generators/client/templates/angular
Error: Template file webpack/environment.js was not found at /Volumes/CWork/0--Original/jhipster/middle-santander/jhipster-dotnetcore-3.1.1/generators/client/templates/angular,/usr/local/lib/node_modules/generator-jhipster/generators/client/templates/angular
    at /Volumes/CWork/0--Original/jhipster/middle-santander/jhipster-dotnetcore-3.1.1/node_modules/generator-jhipster/generators/generator-base.js:2209:25
    at Array.map (<anonymous>)
    at /Volumes/CWork/0--Original/jhipster/middle-santander/jhipster-dotnetcore-3.1.1/node_modules/generator-jhipster/generators/generator-base.js:2139:42
    at Array.map (<anonymous>)
    at /Volumes/CWork/0--Original/jhipster/middle-santander/jhipster-dotnetcore-3.1.1/node_modules/generator-jhipster/generators/generator-base.js:2136:29
    at Array.map (<anonymous>)
    at module.exports.writeFilesToDisk (/Volumes/CWork/0--Original/jhipster/middle-santander/jhipster-dotnetcore-3.1.1/node_modules/generator-jhipster/generators/generator-base.js:2135:45)
    at module.exports.writeFiles (/Volumes/CWork/0--Original/jhipster/middle-santander/jhipster-dotnetcore-3.1.1/node_modules/generator-jhipster/generators/client/files-angular.js:521:15)
    at module.exports.writeFilesDotnetcore (/Volumes/CWork/0--Original/jhipster/middle-santander/jhipster-dotnetcore-3.1.1/generators/client/index.js:118:47)
    at Object.<anonymous> (/Volumes/CWork/0--Original/jhipster/middle-santander/jhipster-dotnetcore-3.1.1/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:1024:25)

**Comment by cvillami** [comment]
The only release that does not give the above error is 3.0.0

> (base) cvillami@ToreToto poclg % npm ls --global generator-jhipster
/usr/local/lib
├─┬ generator-jhipster-dotnetcore@3.0.0
│ └── generator-jhipster@7.0.1
└── generator-jhipster@7.0.1

**Comment by nicolas63** [comment]
Oh yes, that's because 3.0 is compatible with 7.0 and 3.1 with 7.1. Sorry, we really need a compatibility matrix. If you want contribute maybe you can add it ?

**Comment by 123445666** [comment]
I fixed the angular issue with jhipster 7.6 on my forked branch, it works well for me, you can use it for save your time if you want.
https://github.com/123445666/jhipster-dotnetcore/tree/issue-918

**Comment by nicolas63** [comment]
Very Nice @123445666 ! Can you create a PR ?

**Comment by 123445666** [comment]
Sure, i've just done it.

**Comment by nicolas63** [comment]
Jhipster dotnet 3.2 is released and support jhipster 7.6
