### ISSUE TITLE
Join dotnet foundation 

### ISSUE THREAD

**Issue by nicolas63** [jhipster/jhipster-dotnetcore#93]
https://github.com/dotnet/foundation/blob/master/guidance/new-projects.md

Check all requirement and ask to join dotnet foundation

**Comment by nicolas63** [comment]
@danielpetisme you can follow this ? I can help you if you want.

**Comment by nicolas63** [comment]
## 1.   General Information

**Project Name:** 

JHipster.NET blueprint 

**License:**

Apache-2.0

**Contributor (Company, Organization or individual name(s)):**
The project is under JHipster Organization 

Top five contributor : 

@danielpetisme
@nicolas63
@BananeGuimauve
@maznag
@AdrianDo

**Existing OSS Project? (Yes/No):**

Yes

**Source Code URL:**

https://github.com/jhipster/jhipster-dotnetcore

**Project Homepage URL (if different):**

**Project Transfer Signatories:**
Full legal name and email address required of the individual(s) with the authority to transfer or contribute the project to the .NET Foundation. Note that if you'd prefer not to include this in the public application, it can be submitted via e-mail to contact@dotnetfoundation.org (referencing this issue number).

Will be submitted via e-mail to contact@dotnetfoundation.org.

## 2.   Description
**Please provide a brief statement about your project in terms that are understandable to the target consumer of the library or project, i.e. an elevator pitch for the project:**

Generate a jhispter app with asp.net core as back end 

**Please provide a 1 sentence (<140 character) summary of your to help users when searching the .NET Foundation projects**

 jhispter app with asp.net core as back end 

## 3.   Project Governance
Please complete this section about who will be maintaining the open source project and how it will run.
**Project Lead:**
(Who is the primary contact point for the community and the .NET Foundation when discussing governance of the project.)

Name:   Daniel petisme 
 Email:   daniel.petisme@gmail.com
 GitHub Profile URL: https://github.com/danielpetisme

**Committers:**
<em>
Which individuals have commit / write access to the repository, what is their GitHub ID and who is their employer (if contributions are on behalf of an employer)
</em>

@jhipster/jhipster-net-admins
and @jhipster/jhipster-net-developers

**Governance Model:**
<em>
Please describe how new code changes are proposed to the project, how those changes are reviewed and how a decision is made to accept proposed changes. Also describe the process for identifying and appointing new committers.
</em>

Changes are proposed in GitHub Issues, Pull Requests. Changes are reviewed by the core contributors and the community.

**CLA**

<em>
If already an OSS project, was a Contribution License Agreement in place for contributions accepted? How does the project check who has signed one?
</em>

No

**CLA Notification Alias**
Provide an email address that will receive CLA related notifications from the .NET Foundation CLA automation

n/a

**Project Transfer Type**

<em>
Projects may join the .NET Foundation in one of two ways and you should chat with your .NET Foundation contact to discuss the best mechanism for your project. You can either a) assign the copyright of the project's source code to the .NET Foundation or b) contribute the project source code to the .NET Foundation under an open source license. Assignment is the preferred approach, but licensing a project to the Foundation may be more appropriate for longer running open source projects that have not previously had a contribution license agreement and have accepted contributions from many different sources.
a) Assignment
b) Contribution
</em>
<br/><br/>
b) Contribution

## 4.   Repository Layout
<em>
The .NET Foundation host guidance for new projects and details on recommended structure here:
[https://github.com/dotnet/home/tree/master/guidance](https://github.com/dotnet/home/tree/master/guidance)

Note that the open source repository should be the master where changes are made by the core development team using the same PR process that is used for non-committer contributions.

Please define below any changes you would want to make to your repositories as part of the process of joining the .NET Foundation
</em>

## 5.   PR Plan
<em>
Please summarize the public relations plan for the announcement when joining the foundation (and releasing as open source if appropriate). What is the main story we wish to promote, through what channels, what issues should we be aware of?  For significant news events then please also work with your .NET Foundation contact to ensure a [full PR plan](https://dotnetfoundation.sharepoint.com/Shared%20Documents/PR/Communications%20Plan%20TEMPLATE.docx?web=1) is developed.
</em>
<br/><br/>
twitter announcement (https://twitter.com/jhipster?lang=fr)

## 6.   Infrastructure Requirements
<em>
Please describe any infrastructure requirements for the project. For example, how will build servers be operated? Any web hosting or service hosting requirements? Do we need to set up SSL certificates or provide Authenticode Code Signing arrangement for releases?
</em>
<br/><br/>
n/a

## 7.   Additional Notes
<em>
Please provide any additional information required or use this area for notes during the onboarding process. If this open source project has similarities with any other projects in this space then please detail them and why this project is different. If there are any potential issues that you feel the project might need help with early on then also state them here and discuss with your .NET Foundation Contact.
</em>

**Comment by nicolas63** [comment]
@danielpetisme What do you think of that ? The is the on boarding issue on ( https://github.com/dotnet-foundation/projects/issue)

**Comment by nicolas63** [comment]
@jhipster/developers what do you think if this blueprint joins the .NET foundation ?

**Comment by nicolas63** [comment]
https://dotnetfoundation.org/

**Comment by deepu105** [comment]
If it helps the project in anyway I'm all for it

**Comment by danielpetisme** [comment]
You definitely have my +1.
As always, struggling with time.
Feel free to start @nicolas63 , it's easier for me to support rather than lead this subject

**Comment by nicolas63** [comment]
https://github.com/dotnet-foundation/projects/issues/61

**Comment by nicolas63** [comment]
```
Hi Daniel,
 
My apologies for the delay in communication. The Project Committee and Board of Directors both discussed the JHipster.Net application during last month’s meetings and there were a couple main areas of feedback:
 
1.	The Project Health metrics as defined by the .NET Foundation ( ie. commits, forks, issues, etc… ) were quite low in comparison to other .NET Foundation projects. This would tend to indicate that the project is still early in its maturity cycle and it would be best to revisit the project in the future when it has more traction. We realize that the parent project for JHipster is already very well established so the feedback is more focused on the .NET Core variant ( as this is the version being evaluated in this application ). Sometimes projects which have lower level of maturity are accepted into the Seed level for the .NET Foundation – which is essentially an incubator program of sorts. However, JHipster.Net was not promoted to this level because of item #2 below.
2.	There was discussion about whether the .NET Foundation should accept open source projects which are sub-projects of larger open source projects – or if it should focus only on the larger open source projects themselves ( so far the .NET Foundation has taken the latter approach ). For example, many open source projects have extensibility models which allow you to build custom plug-ins. And if those plug-ins are available under an open source license, does it make sense to include them in the .NET Foundation? There is more discussion needed in this area before a decision can be made.
 
I hope this level of transparency is helpful, and I also hope you appreciate the challenges of managing an open source foundation like the .NET Foundation. If you have further comments or questions, please let me know.
 
Thank you,
Shaun Walker
```
