### ISSUE TITLE
Fix dotnet format integration tests

### ISSUE THREAD

**Issue by ivanmonteiro** [jhipster/jhipster-dotnetcore#937]
##### **Overview of the issue**

After the upgrade to dotnet 6, the `dotnet format` tool is not working.

##### **Reproduce the error**

Run `dotnet format --verify-no-changes`
Error:
```
Unhandled exception: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load file or assembly 'Microsoft.CodeAnalysis.CSharp, Version=4.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. O sistema não pode encontrar o arquivo especificado.
```

##### **Related issues**

https://github.com/dotnet/format/issues/1519

##### **Suggest a Fix**

Waiting for a fix to un-comment lines on file https://github.com/jhipster/jhipster-dotnetcore/blob/main/test-integration/scripts/09-verify-format.sh

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by nicolas63** [comment]
seem work with last version => https://github.com/dotnet/format/issues/1519#issuecomment-1097617862

**Comment by ivanmonteiro** [comment]
> seems work with last version => [dotnet/format#1519 (comment)](https://github.com/dotnet/format/issues/1519#issuecomment-1097617862)

I'm testing it right now and I'll provide a PR if it works :)
