### ISSUE TITLE
Add SonarCloud analysis on generator 

### ISSUE THREAD

**Issue by nicolas63** [jhipster/jhipster-dotnetcore#97]
@deepu105, @pascalgrimaud or @jdubois can you create the project on sonarcloud ?

**Comment by pascalgrimaud** [comment]
I'll take care of it

**Comment by nicolas63** [comment]
In same time, it is possible to add me in @jhipster/jhipster-net-admins ? (To be able to add github secret)

**Comment by pascalgrimaud** [comment]
Here the information
- project key: jhipster_jhipster-dotnetcore
- organization key: jhipster

The SONAR_TOKEN was added to GitHub secrets.
First analyze was done when I linked SonarCloud to this project: https://sonarcloud.io/dashboard?id=jhipster_jhipster-dotnetcore

**Comment by pascalgrimaud** [comment]
> In same time, it is possible to add me in @jhipster/jhipster-net-admins ? (To be able to add github secret)

done

**Comment by pascalgrimaud** [comment]
@nicolas63 : I'll let you add the Sonar Analyze to GitHub Actions, to check if it works well. Once you confirmed it, I'll let you close this ticket
Let me know if you encounter problems

**Comment by jdubois** [comment]
@pascalgrimaud you are already an admin, I just checked

**Comment by nicolas63** [comment]
Great, thank you very much 😃 . I test it as soon as possible

**Comment by pascalgrimaud** [comment]
@jdubois : yes I know, but I'd prefer letting @nicolas63 closing this ticket once he's considering the task done :)

**Comment by nicolas63** [comment]
@pascalgrimaud I have the error : 
```You are running CI analysis while Automatic Analysis is enabled. Please consider disabling one or the other.```

Can you disable automatic analysis in sonarcloud ?

**Comment by pascalgrimaud** [comment]
I don't know how to disable automatic analysis, maybe I can remove https://sonarcloud.io/dashboard?id=jhipster_jhipster-dotnetcore then, you'll try to push a new analysis ?

**Comment by pascalgrimaud** [comment]
@nicolas63 : just done (disable), can you retry plz ?

**Comment by nicolas63** [comment]
@pascalgrimaud It works, thank you !

**Comment by danielpetisme** [comment]
Hello,

Nicolas can I tweet the Sonar dashboard? The start are quite good IMHO with
the maturity we have.
Daniel PETISME
daniel.petisme@gmail.com

**Comment by nicolas63** [comment]
yes you can, but with minimal effort we can improve on that. It is better to wait no ?

**Comment by danielpetisme** [comment]
As you prefer.

**Comment by nicolas63** [comment]
@danielpetisme it is better now 😃 (https://sonarcloud.io/dashboard?id=jhipster_jhipster-dotnetcore)

**Comment by pascalgrimaud** [comment]
don't forget, you can add the badge in readme now

**Comment by nicolas63** [comment]
yes, i do this now

**Comment by danielpetisme** [comment]
Arf I thought it was the quality of the generated project and not the
generator itself :/

Anyway super work Nico!
Daniel PETISME
daniel.petisme@gmail.com

**Comment by nicolas63** [comment]
ah ah, no i will publish the app analysis after #90
