### ISSUE TITLE
Issue related many-to-many relationship

### ISSUE THREAD

**Issue by 123445666** [jhipster/jhipster-dotnetcore#976]
Hi @nicolas63 ,

##### **Overview of the issue**

When working with Dao issue, i found a bug related many-to-many relationship with ef.

##### **Motivation for or Use Case**
Create or edit a Job History and Save.
It shows : 'UNIQUE constraint failed: JobChores.ChoresId, JobChores.JobsId'."

##### **Reproduce the error**

I used the app.jdl in the test folder but commented the dto line.

##### **Suggest a Fix**

My solution is:
I'll change this function AddOrUpdateGraph like below.

```
public void AddOrUpdateGraph<TEntiy>(TEntiy entity, List<string> entitiesToBeUpdated = null) where TEntiy : class
{
          var rootTypeEntity = entity.GetType().Name;
         _context.ChangeTracker.TrackGraph(entity, e =>
          {
              string navigationPropertyName = e.Entry.Entity.GetType().Name;

              var alreadyTrackedEntity = _context.ChangeTracker.Entries().FirstOrDefault(entry => entry.Entity.Equals(e.Entry.Entity));

              if (alreadyTrackedEntity != null)
              {
                  alreadyTrackedEntity.State = EntityState.Detached;
              }
              if (navigationPropertyName != rootTypeEntity && !(entitiesToBeUpdated != null && entitiesToBeUpdated.Contains(navigationPropertyName)))
              {
                  e.Entry.State = EntityState.Unchanged;
              }
              else if (e.Entry.IsKeySet)
              {
                  e.Entry.State = EntityState.Modified;
              }
              else
              {
                  e.Entry.State = EntityState.Added;
              }
          });
}
```

Do you think it's ok ? If ok, i'll make the pull request. Thank you.

##### **Browsers and Operating System**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by nicolas63** [comment]
Yes i think is good, @ivanmonteiro are you also agree ? 
@123445666 What do you pass in parameter entitiesToBeUpdated ?

**Comment by 123445666** [comment]
@nicolas63 With the new AddOrUpdateGraph, it'll only update the root Entity (without the child) except "many-to-many relation"

If there are "many-to-many", it'll pass the name of child entity like this 
`List<string> entitiesToBeUpdated = new List<string> { "PieceOfWork" };
return await base.CreateOrUpdateAsync(job, entitiesToBeUpdated);`

* It will also avoid the risk of unexpected child data updates with TrackGraph

**Comment by nicolas63** [comment]
Maybe it's better to pass a type like 
List<Type> { typeof(PieceOfWork) };
return await base.CreateOrUpdateAsync(job, entitiesToBeUpdated);

Are you ok with this ?

**Comment by 123445666** [comment]
It's ok, i'll do it that way.

**Comment by ivanmonteiro** [comment]
> Yes i think is good, @ivanmonteiro are you also agree ? @123445666 What do you pass in parameter entitiesToBeUpdated ?

I agree, for the moment we can try @123445666's approach.
